<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Pangan extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        DB::table('pangan')->delete();

        DB::table('pangan')->insert(array (
            0 =>
            array (
                'id_pangan' => 1,
            'nama_pangan' => '    Beras (beras lokal, kualitas unggul, impor)',
                'gram' => '1000.00',
                'kalori' => '3622.00',
                'lemak' => '14.50',
                'karbohidrat' => '775.50',
                'protein' => '84.75',
                'id_jenis_pangan' => 1,
                'id_takaran' => 1,
                'referensi_urt' => '3/4 gelas',
                'referensi_gram_berat' => '100',
            ),
            1 =>
            array (
                'id_pangan' => 2,
                'nama_pangan' => '    Beras ketan',
                'gram' => '1000.00',
                'kalori' => '3605.00',
                'lemak' => '15.50',
                'karbohidrat' => '764.50',
                'protein' => '77.00',
                'id_jenis_pangan' => 1,
                'id_takaran' => 1,
                'referensi_urt' => '3/4 gelas',
                'referensi_gram_berat' => '100',
            ),
            2 =>
            array (
                'id_pangan' => 3,
                'nama_pangan' => '    Jagung basah dengan kulit',
                'gram' => '1000.00',
                'kalori' => '361.20',
                'lemak' => '3.64',
                'karbohidrat' => '84.84',
                'protein' => '11.48',
                'id_jenis_pangan' => 1,
                'id_takaran' => 1,
                'referensi_urt' => '1 buah ukuran sedang',
                'referensi_gram_berat' => '125',
            ),
            3 =>
            array (
                'id_pangan' => 4,
                'nama_pangan' => '    Jagung pipilan/beras jagung/jagung titi',
                'gram' => '1000.00',
                'kalori' => '3200.00',
                'lemak' => '39.00',
                'karbohidrat' => '663.30',
                'protein' => '82.80',
                'id_jenis_pangan' => 1,
                'id_takaran' => 1,
                'referensi_urt' => '1 porsi',
                'referensi_gram_berat' => '82',
            ),
            4 =>
            array (
                'id_pangan' => 5,
                'nama_pangan' => '    Tepung terigu',
                'gram' => '1000.00',
                'kalori' => '3330.00',
                'lemak' => '10.00',
                'karbohidrat' => '772.00',
                'protein' => '90.00',
                'id_jenis_pangan' => 1,
                'id_takaran' => 1,
                'referensi_urt' => '5 sendok makan',
                'referensi_gram_berat' => '50',
            ),
            5 =>
            array (
                'id_pangan' => 6,
                'nama_pangan' => '    Padi-padian lainnya :',
                'gram' => '1000.00',
                'kalori' => '3570.00',
                'lemak' => '9.00',
                'karbohidrat' => '762.00',
                'protein' => '73.00',
                'id_jenis_pangan' => 1,
                'id_takaran' => 1,
                'referensi_urt' => '1 Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            6 =>
            array (
                'id_pangan' => 7,
                'nama_pangan' => '    Ketela pohon/singkong',
                'gram' => '1000.00',
                'kalori' => '1309.00',
                'lemak' => '2.55',
                'karbohidrat' => '312.80',
                'protein' => '8.50',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => '1,5 potong',
                'referensi_gram_berat' => '120',
            ),
            7 =>
            array (
                'id_pangan' => 8,
                'nama_pangan' => '    Ketela rambat/ubi jalar',
                'gram' => '1000.00',
                'kalori' => '1252.00',
                'lemak' => '3.26',
                'karbohidrat' => '293.68',
                'protein' => '11.78',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => '1 biji sedang',
                'referensi_gram_berat' => '135',
            ),
            8 =>
            array (
                'id_pangan' => 9,
            'nama_pangan' => '    Sagu (bukan dari ketela pohon)',
                'gram' => '1000.00',
                'kalori' => '3380.00',
                'lemak' => '3.00',
                'karbohidrat' => '831.00',
                'protein' => '6.00',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => '8 sendok makan',
                'referensi_gram_berat' => '50',
            ),
            9 =>
            array (
                'id_pangan' => 10,
                'nama_pangan' => '    Talas/keladi',
                'gram' => '1000.00',
                'kalori' => '1135.40',
                'lemak' => '3.78',
                'karbohidrat' => '257.31',
                'protein' => '15.50',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => '1/2 biji sedang',
                'referensi_gram_berat' => '125',
            ),
            10 =>
            array (
                'id_pangan' => 11,
                'nama_pangan' => '    Kentang',
                'gram' => '1000.00',
                'kalori' => '520.80',
                'lemak' => '1.68',
                'karbohidrat' => '113.40',
                'protein' => '17.64',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => '2 buah sedang',
                'referensi_gram_berat' => '210',
            ),
            11 =>
            array (
                'id_pangan' => 12,
                'nama_pangan' => '    Gaplek',
                'gram' => '1000.00',
                'kalori' => '3380.00',
                'lemak' => '7.00',
                'karbohidrat' => '813.00',
                'protein' => '15.00',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            12 =>
            array (
                'id_pangan' => 13,
                'nama_pangan' => '    Umbi-umbian lainnya :',
                'gram' => '1000.00',
                'kalori' => '3014.83',
                'lemak' => '1.75',
                'karbohidrat' => '432.27',
                'protein' => '13.00',
                'id_jenis_pangan' => 2,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            13 =>
            array (
                'id_pangan' => 14,
                'nama_pangan' => '    Ekor kuning',
                'gram' => '1000.00',
                'kalori' => '872.00',
                'lemak' => '32.00',
                'karbohidrat' => '0.00',
                'protein' => '136.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong',
                'referensi_gram_berat' => '47.8',
            ),
            14 =>
            array (
                'id_pangan' => 15,
                'nama_pangan' => '    Tongkol',
                'gram' => '1000.00',
                'kalori' => '904.00',
                'lemak' => '15.00',
                'karbohidrat' => '80.00',
                'protein' => '137.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 ekor sedang',
                'referensi_gram_berat' => '100',
            ),
            15 =>
            array (
                'id_pangan' => 16,
                'nama_pangan' => '    Tuna',
                'gram' => '1000.00',
                'kalori' => '904.00',
                'lemak' => '49.00',
                'karbohidrat' => '0.00',
                'protein' => '233.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang',
                'referensi_gram_berat' => '100',
            ),
            16 =>
            array (
                'id_pangan' => 17,
                'nama_pangan' => '    Cakalang, dencis',
                'gram' => '1000.00',
                'kalori' => '904.00',
                'lemak' => '7.00',
                'karbohidrat' => '55.00',
                'protein' => '196.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang',
                'referensi_gram_berat' => '100',
            ),
            17 =>
            array (
                'id_pangan' => 18,
                'nama_pangan' => '    Tenggiri',
                'gram' => '1000.00',
                'kalori' => '904.00',
                'lemak' => '36.00',
                'karbohidrat' => '0.00',
                'protein' => '136.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang',
                'referensi_gram_berat' => '100',
            ),
            18 =>
            array (
                'id_pangan' => 19,
                'nama_pangan' => '    Selar',
                'gram' => '1000.00',
                'kalori' => '480.00',
                'lemak' => '10.56',
                'karbohidrat' => '0.00',
                'protein' => '90.24',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 porsi',
                'referensi_gram_berat' => '90',
            ),
            19 =>
            array (
                'id_pangan' => 20,
                'nama_pangan' => '    Kembung, lema/tatare, banyar/banyara',
                'gram' => '1000.00',
                'kalori' => '824.00',
                'lemak' => '8.00',
                'karbohidrat' => '0.00',
                'protein' => '176.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1/3 ekor sedang',
                'referensi_gram_berat' => '45',
            ),
            20 =>
            array (
                'id_pangan' => 21,
                'nama_pangan' => '    Teri basah',
                'gram' => '1000.00',
                'kalori' => '740.00',
                'lemak' => '14.00',
                'karbohidrat' => '41.00',
                'protein' => '103.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 sdm',
                'referensi_gram_berat' => '15',
            ),
            21 =>
            array (
                'id_pangan' => 22,
                'nama_pangan' => '    Bandeng',
                'gram' => '1000.00',
                'kalori' => '1032.00',
                'lemak' => '38.40',
                'karbohidrat' => '0.00',
                'protein' => '160.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong',
                'referensi_gram_berat' => '82',
            ),
            22 =>
            array (
                'id_pangan' => 23,
                'nama_pangan' => '    Gabus',
                'gram' => '1000.00',
                'kalori' => '477.40',
                'lemak' => '6.20',
                'karbohidrat' => '22.94',
                'protein' => '76.88',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 ekor',
                'referensi_gram_berat' => '212.2',
            ),
            23 =>
            array (
                'id_pangan' => 24,
                'nama_pangan' => '    Mujair',
                'gram' => '1000.00',
                'kalori' => '712.00',
                'lemak' => '8.00',
                'karbohidrat' => '0.00',
                'protein' => '149.60',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1/3 ekor sedang',
                'referensi_gram_berat' => '30',
            ),
            24 =>
            array (
                'id_pangan' => 25,
                'nama_pangan' => '    Mas',
                'gram' => '1000.00',
                'kalori' => '688.00',
                'lemak' => '20.00',
                'karbohidrat' => '0.00',
                'protein' => '160.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1/3 ekor sedang',
                'referensi_gram_berat' => '45',
            ),
            25 =>
            array (
                'id_pangan' => 26,
                'nama_pangan' => '    Nila',
                'gram' => '1000.00',
                'kalori' => '688.00',
                'lemak' => '10.00',
                'karbohidrat' => '0.00',
                'protein' => '187.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 porsi',
                'referensi_gram_berat' => '100',
            ),
            26 =>
            array (
                'id_pangan' => 27,
                'nama_pangan' => '    Lele',
                'gram' => '1000.00',
                'kalori' => '477.40',
                'lemak' => '6.20',
                'karbohidrat' => '22.94',
                'protein' => '76.88',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1/3 ekor sedang',
                'referensi_gram_berat' => '40',
            ),
            27 =>
            array (
                'id_pangan' => 28,
                'nama_pangan' => '    Kakap',
                'gram' => '1000.00',
                'kalori' => '736.00',
                'lemak' => '5.60',
                'karbohidrat' => '0.00',
                'protein' => '160.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1/3 ekor besar',
                'referensi_gram_berat' => '35',
            ),
            28 =>
            array (
                'id_pangan' => 29,
                'nama_pangan' => '    Baronang',
                'gram' => '1000.00',
                'kalori' => '1200.00',
                'lemak' => '53.00',
                'karbohidrat' => '4.00',
                'protein' => '165.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 porsi',
                'referensi_gram_berat' => '85',
            ),
            29 =>
            array (
                'id_pangan' => 30,
                'nama_pangan' => '    Patin',
                'gram' => '1000.00',
                'kalori' => '477.40',
                'lemak' => '6.20',
                'karbohidrat' => '22.94',
                'protein' => '76.88',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 porsi',
                'referensi_gram_berat' => '110',
            ),
            30 =>
            array (
                'id_pangan' => 31,
                'nama_pangan' => '    Bawal',
                'gram' => '1000.00',
                'kalori' => '960.00',
                'lemak' => '17.00',
                'karbohidrat' => '0.00',
                'protein' => '190.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 ekor',
                'referensi_gram_berat' => '132.2',
            ),
            31 =>
            array (
                'id_pangan' => 32,
                'nama_pangan' => '    Gurame',
                'gram' => '1000.00',
                'kalori' => '712.00',
                'lemak' => '8.00',
                'karbohidrat' => '0.00',
                'protein' => '149.60',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 porsi',
                'referensi_gram_berat' => '110',
            ),
            32 =>
            array (
                'id_pangan' => 33,
                'nama_pangan' => '    Ikan segar/basah lainnya',
                'gram' => '1000.00',
                'kalori' => '904.00',
                'lemak' => '36.00',
                'karbohidrat' => '0.00',
                'protein' => '136.00',
                'id_jenis_pangan' => 15,
                'id_takaran' => 1,
                'referensi_urt' => '1 Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            33 =>
            array (
                'id_pangan' => 34,
                'nama_pangan' => '    Udang, lobster',
                'gram' => '1000.00',
                'kalori' => '618.80',
                'lemak' => '1.36',
                'karbohidrat' => '0.68',
                'protein' => '142.80',
                'id_jenis_pangan' => 16,
                'id_takaran' => 1,
                'referensi_urt' => '5 ekor sedang ',
                'referensi_gram_berat' => '35',
            ),
            34 =>
            array (
                'id_pangan' => 35,
                'nama_pangan' => '    Cumi-cumi, sotong, gurita',
                'gram' => '1000.00',
                'kalori' => '750.00',
                'lemak' => '7.00',
                'karbohidrat' => '1.00',
                'protein' => '161.00',
                'id_jenis_pangan' => 16,
                'id_takaran' => 1,
                'referensi_urt' => '1 ekor kecil',
                'referensi_gram_berat' => '45',
            ),
            35 =>
            array (
                'id_pangan' => 36,
                'nama_pangan' => '    Ketam, kepiting, rajungan',
                'gram' => '1000.00',
                'kalori' => '679.50',
                'lemak' => '17.10',
                'karbohidrat' => '63.50',
                'protein' => '62.10',
                'id_jenis_pangan' => 16,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            36 =>
            array (
                'id_pangan' => 37,
                'nama_pangan' => '    Kerang, siput, bekicot, remis',
                'gram' => '1000.00',
                'kalori' => '1010.00',
                'lemak' => '26.00',
                'karbohidrat' => '39.00',
                'protein' => '144.00',
                'id_jenis_pangan' => 16,
                'id_takaran' => 1,
                'referensi_urt' => '1/2 gelas',
                'referensi_gram_berat' => '90',
            ),
            37 =>
            array (
                'id_pangan' => 38,
                'nama_pangan' => '    Udang dan hewan air lainnya yang segar lainnya',
                'gram' => '1000.00',
                'kalori' => '552.20',
                'lemak' => '8.30',
                'karbohidrat' => '8.10',
                'protein' => '108.60',
                'id_jenis_pangan' => 16,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            38 =>
            array (
                'id_pangan' => 39,
                'nama_pangan' => '    Kembung diawetkan/peda',
                'gram' => '100.00',
                'kalori' => '140.40',
                'lemak' => '3.60',
                'karbohidrat' => '0.00',
                'protein' => '25.20',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => 'Ons',
                'referensi_gram_berat' => ' 100.0 ',
            ),
            39 =>
            array (
                'id_pangan' => 40,
                'nama_pangan' => '    Tenggiri diawetkan',
                'gram' => '100.00',
                'kalori' => '135.10',
                'lemak' => '1.05',
                'karbohidrat' => '0.00',
                'protein' => '29.40',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => 'Ons',
                'referensi_gram_berat' => ' 100.0 ',
            ),
            40 =>
            array (
                'id_pangan' => 41,
                'nama_pangan' => '    Tongkol, tuna, cakalang, dencis, ikan kayu diawetkan',
                'gram' => '100.00',
                'kalori' => '138.60',
                'lemak' => '1.54',
                'karbohidrat' => '3.85',
                'protein' => '25.55',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => '1 potong sedang',
                'referensi_gram_berat' => '20',
            ),
            41 =>
            array (
                'id_pangan' => 42,
                'nama_pangan' => '    Teri diawetkan',
                'gram' => '100.00',
                'kalori' => '230.50',
                'lemak' => '2.52',
                'karbohidrat' => '0.45',
                'protein' => '48.65',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => '1 sendok makan',
                'referensi_gram_berat' => '20',
            ),
            42 =>
            array (
                'id_pangan' => 43,
                'nama_pangan' => '    Selar diawetkan',
                'gram' => '100.00',
                'kalori' => '145.50',
                'lemak' => '2.62',
                'karbohidrat' => '0.00',
                'protein' => '28.50',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => '1 ekor',
                'referensi_gram_berat' => '20',
            ),
            43 =>
            array (
                'id_pangan' => 44,
                'nama_pangan' => '    Sepat diawetkan',
                'gram' => '100.00',
                'kalori' => '216.80',
                'lemak' => '10.50',
                'karbohidrat' => '0.00',
                'protein' => '28.50',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => '1 potong sedang',
                'referensi_gram_berat' => '20',
            ),
            44 =>
            array (
                'id_pangan' => 45,
                'nama_pangan' => '    Bandeng diawetkan',
                'gram' => '100.00',
                'kalori' => '296.00',
                'lemak' => '20.30',
                'karbohidrat' => '11.30',
                'protein' => '17.10',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => 'Ons',
                'referensi_gram_berat' => ' 100.0 ',
            ),
            45 =>
            array (
                'id_pangan' => 46,
                'nama_pangan' => '    Gabus diawetkan',
                'gram' => '100.00',
                'kalori' => '233.60',
                'lemak' => '3.20',
                'karbohidrat' => '0.00',
                'protein' => '46.40',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => '1 ekor kecil',
                'referensi_gram_berat' => '10',
            ),
            46 =>
            array (
                'id_pangan' => 47,
            'nama_pangan' => '    Ikan dalam kaleng (sardencis, tuna dalam kaleng, dsb)',
                'gram' => '100.00',
                'kalori' => '338.00',
                'lemak' => '27.00',
                'karbohidrat' => '0.00',
                'protein' => '21.10',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => '1/2 potong',
                'referensi_gram_berat' => '35',
            ),
            47 =>
            array (
                'id_pangan' => 48,
                'nama_pangan' => '    Ikan diawetkan lainnya',
                'gram' => '100.00',
                'kalori' => '305.00',
                'lemak' => '8.90',
                'karbohidrat' => '10.86',
                'protein' => '43.62',
                'id_jenis_pangan' => 17,
                'id_takaran' => 2,
                'referensi_urt' => 'Ons',
                'referensi_gram_berat' => ' 100.0 ',
            ),
            48 =>
            array (
                'id_pangan' => 49,
            'nama_pangan' => '    Udang (ebi, rebon)',
                'gram' => '100.00',
                'kalori' => '265.50',
                'lemak' => '2.07',
                'karbohidrat' => '1.60',
                'protein' => '56.16',
                'id_jenis_pangan' => 18,
                'id_takaran' => 2,
                'referensi_urt' => '2 sendok makan',
                'referensi_gram_berat' => '10',
            ),
            49 =>
            array (
                'id_pangan' => 50,
                'nama_pangan' => '    Cumi-cumi, sotong, gurita diawetkan',
                'gram' => '100.00',
                'kalori' => '265.50',
                'lemak' => '2.07',
                'karbohidrat' => '1.60',
                'protein' => '56.16',
                'id_jenis_pangan' => 18,
                'id_takaran' => 2,
                'referensi_urt' => '2 sendok makan',
                'referensi_gram_berat' => '10',
            ),
            50 =>
            array (
                'id_pangan' => 51,
                'nama_pangan' => '    Udang dan hewan air lainnya yang diawetkan',
                'gram' => '100.00',
                'kalori' => '357.00',
                'lemak' => '10.00',
                'karbohidrat' => '25.60',
                'protein' => '41.10',
                'id_jenis_pangan' => 18,
                'id_takaran' => 2,
                'referensi_urt' => 'Ons',
                'referensi_gram_berat' => ' 100.0 ',
            ),
            51 =>
            array (
                'id_pangan' => 52,
                'nama_pangan' => '    Daging sapi',
                'gram' => '1000.00',
                'kalori' => '2070.00',
                'lemak' => '140.00',
                'karbohidrat' => '0.00',
                'protein' => '188.00',
                'id_jenis_pangan' => 19,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang ',
                'referensi_gram_berat' => '50',
            ),
            52 =>
            array (
                'id_pangan' => 53,
                'nama_pangan' => '    Daging kambing, domba/biri-biri',
                'gram' => '1000.00',
                'kalori' => '1540.00',
                'lemak' => '92.00',
                'karbohidrat' => '0.00',
                'protein' => '166.00',
                'id_jenis_pangan' => 19,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang ',
                'referensi_gram_berat' => '40',
            ),
            53 =>
            array (
                'id_pangan' => 54,
                'nama_pangan' => '    Daging babi',
                'gram' => '1000.00',
                'kalori' => '4165.00',
                'lemak' => '400.00',
                'karbohidrat' => '0.00',
                'protein' => '130.00',
                'id_jenis_pangan' => 19,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang ',
                'referensi_gram_berat' => '50',
            ),
            54 =>
            array (
                'id_pangan' => 55,
                'nama_pangan' => '    Daging ayam ras',
                'gram' => '1000.00',
                'kalori' => '3020.00',
                'lemak' => '250.00',
                'karbohidrat' => '0.00',
                'protein' => '182.00',
                'id_jenis_pangan' => 19,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang ',
                'referensi_gram_berat' => '50',
            ),
            55 =>
            array (
                'id_pangan' => 56,
                'nama_pangan' => '    Daging ayam kampung',
                'gram' => '1000.00',
                'kalori' => '3020.00',
                'lemak' => '250.00',
                'karbohidrat' => '0.00',
                'protein' => '182.00',
                'id_jenis_pangan' => 19,
                'id_takaran' => 1,
                'referensi_urt' => '1 potong sedang ',
                'referensi_gram_berat' => '50',
            ),
            56 =>
            array (
                'id_pangan' => 57,
                'nama_pangan' => '    Daging segar lainnya :',
                'gram' => '1000.00',
                'kalori' => '2050.00',
                'lemak' => '148.00',
                'karbohidrat' => '0.00',
                'protein' => '171.00',
                'id_jenis_pangan' => 19,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            57 =>
            array (
                'id_pangan' => 58,
            'nama_pangan' => '    Daging diawetkan (sosis, abon, nugget, lainnya)',
                'gram' => '1000.00',
                'kalori' => '3385.69',
                'lemak' => '423.00',
                'karbohidrat' => '23.00',
                'protein' => '145.00',
                'id_jenis_pangan' => 20,
                'id_takaran' => 1,
                'referensi_urt' => '1/2 potong',
                'referensi_gram_berat' => '50',
            ),
            58 =>
            array (
                'id_pangan' => 59,
                'nama_pangan' => '    Tetelan, sandung lamur',
                'gram' => '1000.00',
                'kalori' => '1280.00',
                'lemak' => '65.00',
                'karbohidrat' => '8.00',
                'protein' => '155.30',
                'id_jenis_pangan' => 21,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            59 =>
            array (
                'id_pangan' => 60,
            'nama_pangan' => '    Lainnya (hati, jeroan, iga, kaki, buntut, kepala, dsb)',
                'gram' => '1000.00',
                'kalori' => '1189.58',
                'lemak' => '65.00',
                'karbohidrat' => '8.00',
                'protein' => '155.30',
                'id_jenis_pangan' => 21,
                'id_takaran' => 1,
                'referensi_urt' => 'Kg',
                'referensi_gram_berat' => ' 1,000.0 ',
            ),
            60 =>
            array (
                'id_pangan' => 61,
                'nama_pangan' => '    Telur ayam ras',
                'gram' => '60.00',
                'kalori' => '82.24',
                'lemak' => '5.77',
                'karbohidrat' => '0.37',
                'protein' => '6.62',
                'id_jenis_pangan' => 5,
                'id_takaran' => 3,
                'referensi_urt' => '1 Butir',
                'referensi_gram_berat' => ' 60.0 ',
            ),
            61 =>
            array (
                'id_pangan' => 62,
                'nama_pangan' => '    Telur ayam kampung',
                'gram' => '50.00',
                'kalori' => '68.90',
                'lemak' => '5.32',
                'karbohidrat' => '0.28',
                'protein' => '4.52',
                'id_jenis_pangan' => 5,
                'id_takaran' => 3,
                'referensi_urt' => '1 Butir',
                'referensi_gram_berat' => ' 50.0 ',
            ),
            62 =>
            array (
                'id_pangan' => 63,
                'nama_pangan' => '    Telur itik/telur itik manila',
                'gram' => '70.00',
                'kalori' => '125.40',
                'lemak' => '10.18',
                'karbohidrat' => '0.00',
                'protein' => '7.76',
                'id_jenis_pangan' => 5,
                'id_takaran' => 3,
                'referensi_urt' => '1 Butir',
                'referensi_gram_berat' => ' 70.0 ',
            ),
            63 =>
            array (
                'id_pangan' => 64,
            'nama_pangan' => '    Telur lainnya (telur puyuh, telur asin mentah maupun matang, telur penyu, telur angsa, dsb)',
                'gram' => '43.60',
                'kalori' => '64.20',
                'lemak' => '0.00',
                'karbohidrat' => '0.00',
                'protein' => '4.83',
                'id_jenis_pangan' => 5,
                'id_takaran' => 3,
                'referensi_urt' => '1 Butir',
                'referensi_gram_berat' => ' 43.6 ',
            ),
            64 =>
            array (
                'id_pangan' => 65,
                'nama_pangan' => '    Susu cair pabrik',
                'gram' => '200.00',
                'kalori' => '122.00',
                'lemak' => '7.00',
                'karbohidrat' => '8.60',
                'protein' => '6.40',
                'id_jenis_pangan' => 5,
                'id_takaran' => 12,
            'referensi_urt' => '250ml*)',
            'referensi_gram_berat' => ' 200.0 ',
        ),
        65 =>
        array (
            'id_pangan' => 66,
            'nama_pangan' => '    Susu kental manis',
            'gram' => '397.00',
            'kalori' => '1333.90',
            'lemak' => '39.70',
            'karbohidrat' => '218.35',
            'protein' => '32.55',
            'id_jenis_pangan' => 5,
            'id_takaran' => 13,
        'referensi_urt' => '397gr**)',
        'referensi_gram_berat' => ' 397.0 ',
    ),
    66 =>
    array (
        'id_pangan' => 67,
        'nama_pangan' => '    Susu bubuk',
        'gram' => '1000.00',
        'kalori' => '5090.00',
        'lemak' => '300.00',
        'karbohidrat' => '362.00',
        'protein' => '246.00',
        'id_jenis_pangan' => 5,
        'id_takaran' => 1,
        'referensi_urt' => 'Kg',
        'referensi_gram_berat' => ' 1,000.0 ',
    ),
    67 =>
    array (
        'id_pangan' => 68,
        'nama_pangan' => '    Susu bubuk bayi',
        'gram' => '1000.00',
        'kalori' => '1672.00',
        'lemak' => '36.00',
        'karbohidrat' => '262.00',
        'protein' => '76.00',
        'id_jenis_pangan' => 5,
        'id_takaran' => 1,
        'referensi_urt' => 'Kg',
        'referensi_gram_berat' => ' 1,000.0 ',
    ),
    68 =>
    array (
        'id_pangan' => 69,
        'nama_pangan' => '    Susu lainnya dan hasil lain dari susu',
        'gram' => '100.00',
        'kalori' => '488.00',
        'lemak' => '2.50',
        'karbohidrat' => '4.00',
        'protein' => '3.30',
        'id_jenis_pangan' => 5,
        'id_takaran' => 2,
        'referensi_urt' => 'Ons',
        'referensi_gram_berat' => ' 100.0 ',
    ),
    69 =>
    array (
        'id_pangan' => 70,
        'nama_pangan' => '    Bayam',
        'gram' => '1000.00',
        'kalori' => '113.60',
        'lemak' => '2.84',
        'karbohidrat' => '20.59',
        'protein' => '6.39',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 ikat',
        'referensi_gram_berat' => '200',
    ),
    70 =>
    array (
        'id_pangan' => 71,
        'nama_pangan' => '    Kangkung',
        'gram' => '1000.00',
        'kalori' => '168.00',
        'lemak' => '4.20',
        'karbohidrat' => '23.40',
        'protein' => '20.40',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 ikat',
        'referensi_gram_berat' => '200',
    ),
    71 =>
    array (
        'id_pangan' => 72,
        'nama_pangan' => '    Kol/kubis',
        'gram' => '1000.00',
        'kalori' => '180.00',
        'lemak' => '1.50',
        'karbohidrat' => '39.75',
        'protein' => '10.50',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 mangkok dicincang',
        'referensi_gram_berat' => '117',
    ),
    72 =>
    array (
        'id_pangan' => 73,
    'nama_pangan' => '    Sawi putih (petsai)',
        'gram' => '1000.00',
        'kalori' => '66.00',
        'lemak' => '1.50',
        'karbohidrat' => '10.80',
        'protein' => '6.30',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 mangkok',
        'referensi_gram_berat' => '100',
    ),
    73 =>
    array (
        'id_pangan' => 74,
        'nama_pangan' => '    Sawi hijau',
        'gram' => '1000.00',
        'kalori' => '191.40',
        'lemak' => '2.61',
        'karbohidrat' => '34.80',
        'protein' => '20.01',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 ikat',
        'referensi_gram_berat' => '200',
    ),
    74 =>
    array (
        'id_pangan' => 75,
        'nama_pangan' => '    Buncis',
        'gram' => '1000.00',
        'kalori' => '306.00',
        'lemak' => '2.70',
        'karbohidrat' => '64.80',
        'protein' => '21.60',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 mangkok',
        'referensi_gram_berat' => '100',
    ),
    75 =>
    array (
        'id_pangan' => 76,
        'nama_pangan' => '    Kacang panjang',
        'gram' => '1000.00',
        'kalori' => '276.00',
        'lemak' => '4.60',
        'karbohidrat' => '47.80',
        'protein' => '27.60',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 ikat',
        'referensi_gram_berat' => '100',
    ),
    76 =>
    array (
        'id_pangan' => 77,
        'nama_pangan' => '    Tomat sayur, tomat ceri',
        'gram' => '1000.00',
        'kalori' => '190.00',
        'lemak' => '2.90',
        'karbohidrat' => '39.90',
        'protein' => '9.50',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah',
        'referensi_gram_berat' => '50',
    ),
    77 =>
    array (
        'id_pangan' => 78,
        'nama_pangan' => '    Wortel',
        'gram' => '1000.00',
        'kalori' => '288.00',
        'lemak' => '4.80',
        'karbohidrat' => '63.20',
        'protein' => '8.00',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah besar',
        'referensi_gram_berat' => '100',
    ),
    78 =>
    array (
        'id_pangan' => 79,
        'nama_pangan' => '    Mentimun',
        'gram' => '1000.00',
        'kalori' => '68.70',
        'lemak' => '1.21',
        'karbohidrat' => '13.67',
        'protein' => '3.22',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah kecil',
        'referensi_gram_berat' => '100',
    ),
    79 =>
    array (
        'id_pangan' => 80,
        'nama_pangan' => '    Daun ketela pohon/daun singkong',
        'gram' => '1000.00',
        'kalori' => '635.10',
        'lemak' => '10.44',
        'karbohidrat' => '113.10',
        'protein' => '59.16',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 porsi',
        'referensi_gram_berat' => '50',
    ),
    80 =>
    array (
        'id_pangan' => 81,
        'nama_pangan' => '    Terong',
        'gram' => '1000.00',
        'kalori' => '373.10',
        'lemak' => '5.88',
        'karbohidrat' => '71.44',
        'protein' => '15.32',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah',
        'referensi_gram_berat' => '225',
    ),
    81 =>
    array (
        'id_pangan' => 82,
        'nama_pangan' => '    Tauge',
        'gram' => '1000.00',
        'kalori' => '340.00',
        'lemak' => '12.00',
        'karbohidrat' => '43.00',
        'protein' => '37.00',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 porsi',
        'referensi_gram_berat' => '100',
    ),
    82 =>
    array (
        'id_pangan' => 83,
        'nama_pangan' => '    Labu, labu siam, labu parang',
        'gram' => '1000.00',
        'kalori' => '191.70',
        'lemak' => '1.58',
        'karbohidrat' => '45.61',
        'protein' => '6.08',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 porsi',
        'referensi_gram_berat' => '100',
    ),
    83 =>
    array (
        'id_pangan' => 84,
    'nama_pangan' => '    Bahan sayur sop/cap cay/kimlo (paket)',
        'gram' => '500.00',
        'kalori' => '67.50',
        'lemak' => '5.00',
        'karbohidrat' => '2.50',
        'protein' => '3.25',
        'id_jenis_pangan' => 6,
        'id_takaran' => 14,
        'referensi_urt' => 'Bungkus',
        'referensi_gram_berat' => ' 500.0 ',
    ),
    84 =>
    array (
        'id_pangan' => 85,
    'nama_pangan' => '    Bahan sayur asam/lodeh (paket)',
        'gram' => '600.00',
        'kalori' => '116.00',
        'lemak' => '2.40',
        'karbohidrat' => '20.00',
        'protein' => '2.80',
        'id_jenis_pangan' => 6,
        'id_takaran' => 14,
        'referensi_urt' => 'Bungkus',
        'referensi_gram_berat' => ' 600.0 ',
    ),
    85 =>
    array (
        'id_pangan' => 86,
        'nama_pangan' => '    Nangka muda',
        'gram' => '1000.00',
        'kalori' => '408.00',
        'lemak' => '3.20',
        'karbohidrat' => '90.40',
        'protein' => '16.00',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 porsi',
        'referensi_gram_berat' => ' 100.0 ',
    ),
    86 =>
    array (
        'id_pangan' => 87,
        'nama_pangan' => '    Pepaya muda',
        'gram' => '1000.00',
        'kalori' => '197.60',
        'lemak' => '0.76',
        'karbohidrat' => '37.24',
        'protein' => '15.96',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 bungkus',
        'referensi_gram_berat' => ' 100.0 ',
    ),
    87 =>
    array (
        'id_pangan' => 88,
        'nama_pangan' => '    Jengkol',
        'gram' => '1000.00',
        'kalori' => '1260.00',
        'lemak' => '0.90',
        'karbohidrat' => '259.20',
        'protein' => '56.70',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 porsi',
        'referensi_gram_berat' => ' 125.0 ',
    ),
    88 =>
    array (
        'id_pangan' => 89,
        'nama_pangan' => '    Bawang merah',
        'gram' => '100.00',
        'kalori' => '35.10',
        'lemak' => '0.27',
        'karbohidrat' => '0.18',
        'protein' => '1.35',
        'id_jenis_pangan' => 6,
        'id_takaran' => 2,
        'referensi_urt' => '1 buah',
        'referensi_gram_berat' => ' 8.0 ',
    ),
    89 =>
    array (
        'id_pangan' => 90,
        'nama_pangan' => '    Bawang putih',
        'gram' => '100.00',
        'kalori' => '83.60',
        'lemak' => '0.18',
        'karbohidrat' => '20.33',
        'protein' => '3.96',
        'id_jenis_pangan' => 6,
        'id_takaran' => 2,
        'referensi_urt' => '1 buah',
        'referensi_gram_berat' => ' 8.0 ',
    ),
    90 =>
    array (
        'id_pangan' => 91,
        'nama_pangan' => '    Bawang bombay',
        'gram' => '100.00',
        'kalori' => '43.00',
        'lemak' => '0.20',
        'karbohidrat' => '10.30',
        'protein' => '1.40',
        'id_jenis_pangan' => 6,
        'id_takaran' => 2,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => ' 150.0 ',
    ),
    91 =>
    array (
        'id_pangan' => 92,
        'nama_pangan' => '    Cabe merah',
        'gram' => '1000.00',
        'kalori' => '264.00',
        'lemak' => '2.60',
        'karbohidrat' => '62.10',
        'protein' => '8.50',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => ' 8.0 ',
    ),
    92 =>
    array (
        'id_pangan' => 93,
        'nama_pangan' => '    Cabe hijau',
        'gram' => '1000.00',
        'kalori' => '189.00',
        'lemak' => '2.50',
        'karbohidrat' => '42.60',
        'protein' => '5.70',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => ' 5.0 ',
    ),
    93 =>
    array (
        'id_pangan' => 94,
        'nama_pangan' => '    Cabe rawit',
        'gram' => '1000.00',
        'kalori' => '876.00',
        'lemak' => '20.40',
        'karbohidrat' => '169.22',
        'protein' => '40.00',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => ' 3.5 ',
    ),
    94 =>
    array (
        'id_pangan' => 95,
        'nama_pangan' => '    Sayur-sayuran lainnya',
        'gram' => '1000.00',
        'kalori' => '110.15',
        'lemak' => '5.90',
        'karbohidrat' => '48.82',
        'protein' => '24.96',
        'id_jenis_pangan' => 6,
        'id_takaran' => 1,
        'referensi_urt' => 'Kg',
        'referensi_gram_berat' => ' 1,000.0 ',
    ),
    95 =>
    array (
        'id_pangan' => 96,
        'nama_pangan' => '    Kacang tanah tanpa Kulit',
        'gram' => '1000.00',
        'kalori' => '4520.00',
        'lemak' => '428.00',
        'karbohidrat' => '211.00',
        'protein' => '253.00',
        'id_jenis_pangan' => 7,
        'id_takaran' => 1,
        'referensi_urt' => '2 sendok makan',
        'referensi_gram_berat' => '20',
    ),
    96 =>
    array (
        'id_pangan' => 97,
        'nama_pangan' => '    Kacang kedele',
        'gram' => '1000.00',
        'kalori' => '3810.00',
        'lemak' => '167.00',
        'karbohidrat' => '249.00',
        'protein' => '404.00',
        'id_jenis_pangan' => 7,
        'id_takaran' => 1,
        'referensi_urt' => '2,5 sendok makan',
        'referensi_gram_berat' => '25',
    ),
    97 =>
    array (
        'id_pangan' => 98,
        'nama_pangan' => '    Kacang lainnya',
        'gram' => '1000.00',
        'kalori' => '2988.23',
        'lemak' => '40.06',
        'karbohidrat' => '411.33',
        'protein' => '201.31',
        'id_jenis_pangan' => 7,
        'id_takaran' => 1,
        'referensi_urt' => 'Kg',
        'referensi_gram_berat' => ' 1,000.0 ',
    ),
    98 =>
    array (
        'id_pangan' => 99,
        'nama_pangan' => '    Tahu',
        'gram' => '1000.00',
        'kalori' => '800.00',
        'lemak' => '47.00',
        'karbohidrat' => '8.00',
        'protein' => '109.00',
        'id_jenis_pangan' => 7,
        'id_takaran' => 1,
        'referensi_urt' => '2 potong sedang',
        'referensi_gram_berat' => '100',
    ),
    99 =>
    array (
        'id_pangan' => 100,
        'nama_pangan' => '    Tempe',
        'gram' => '1000.00',
        'kalori' => '1430.00',
        'lemak' => '55.00',
        'karbohidrat' => '114.00',
        'protein' => '120.00',
        'id_jenis_pangan' => 7,
        'id_takaran' => 1,
        'referensi_urt' => '1 potong',
        'referensi_gram_berat' => '25',
    ),
    100 =>
    array (
        'id_pangan' => 101,
        'nama_pangan' => '    Oncom',
        'gram' => '100.00',
        'kalori' => '187.00',
        'lemak' => '6.00',
        'karbohidrat' => '22.60',
        'protein' => '13.00',
        'id_jenis_pangan' => 7,
        'id_takaran' => 2,
        'referensi_urt' => '2 potong besar',
        'referensi_gram_berat' => '50',
    ),
    101 =>
    array (
        'id_pangan' => 102,
        'nama_pangan' => '    Hasil lain dari kacang-kacangan',
        'gram' => '100.00',
        'kalori' => '228.40',
        'lemak' => '10.45',
        'karbohidrat' => '43.20',
        'protein' => '16.15',
        'id_jenis_pangan' => 7,
        'id_takaran' => 2,
        'referensi_urt' => 'Ons',
        'referensi_gram_berat' => ' 100.0 ',
    ),
    102 =>
    array (
        'id_pangan' => 103,
        'nama_pangan' => '    Jeruk, jeruk bali',
        'gram' => '1000.00',
        'kalori' => '311.30',
        'lemak' => '1.60',
        'karbohidrat' => '78.30',
        'protein' => '5.29',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 potong',
        'referensi_gram_berat' => '105',
    ),
    103 =>
    array (
        'id_pangan' => 104,
        'nama_pangan' => '    Mangga',
        'gram' => '1000.00',
        'kalori' => '365.30',
        'lemak' => '1.30',
        'karbohidrat' => '95.03',
        'protein' => '3.64',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '3/4 buah besar',
        'referensi_gram_berat' => '90',
    ),
    104 =>
    array (
        'id_pangan' => 105,
        'nama_pangan' => '    Apel',
        'gram' => '1000.00',
        'kalori' => '484.50',
        'lemak' => '3.40',
        'karbohidrat' => '108.80',
        'protein' => '4.25',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah kecil',
        'referensi_gram_berat' => '85',
    ),
    105 =>
    array (
        'id_pangan' => 106,
        'nama_pangan' => '    Rambutan',
        'gram' => '1000.00',
        'kalori' => '276.00',
        'lemak' => '0.40',
        'karbohidrat' => '72.40',
        'protein' => '3.60',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '8 buah',
        'referensi_gram_berat' => '75',
    ),
    106 =>
    array (
        'id_pangan' => 107,
        'nama_pangan' => '    Duku, langsat',
        'gram' => '1000.00',
        'kalori' => '403.20',
        'lemak' => '1.28',
        'karbohidrat' => '103.04',
        'protein' => '6.40',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '10-16 buah sedang',
        'referensi_gram_berat' => '80',
    ),
    107 =>
    array (
        'id_pangan' => 108,
        'nama_pangan' => '    Durian',
        'gram' => '1000.00',
        'kalori' => '294.80',
        'lemak' => '6.60',
        'karbohidrat' => '61.60',
        'protein' => '5.50',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '2 biji besar',
        'referensi_gram_berat' => '35',
    ),
    108 =>
    array (
        'id_pangan' => 109,
        'nama_pangan' => '    Salak',
        'gram' => '1000.00',
        'kalori' => '1350.60',
        'lemak' => '1.64',
        'karbohidrat' => '329.62',
        'protein' => '4.68',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => '65',
    ),
    109 =>
    array (
        'id_pangan' => 110,
        'nama_pangan' => '    Pisang ambon',
        'gram' => '1000.00',
        'kalori' => '644.00',
        'lemak' => '2.10',
        'karbohidrat' => '168.00',
        'protein' => '7.00',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => '118',
    ),
    110 =>
    array (
        'id_pangan' => 111,
        'nama_pangan' => '    Pisang lainnya ',
        'gram' => '1000.00',
        'kalori' => '1131.10',
        'lemak' => '6.03',
        'karbohidrat' => '264.82',
        'protein' => '10.06',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah sedang',
        'referensi_gram_berat' => '95',
    ),
    111 =>
    array (
        'id_pangan' => 112,
        'nama_pangan' => '    Pepaya',
        'gram' => '1000.00',
        'kalori' => '345.00',
        'lemak' => '0.00',
        'karbohidrat' => '91.50',
        'protein' => '3.75',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 potong besar',
        'referensi_gram_berat' => '100-190',
    ),
    112 =>
    array (
        'id_pangan' => 113,
        'nama_pangan' => '    Semangka',
        'gram' => '1000.00',
        'kalori' => '128.80',
        'lemak' => '0.92',
        'karbohidrat' => '31.74',
        'protein' => '2.30',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '2 potong sedang',
        'referensi_gram_berat' => '180',
    ),
    113 =>
    array (
        'id_pangan' => 114,
        'nama_pangan' => '    Tomat buah',
        'gram' => '1000.00',
        'kalori' => '240.00',
        'lemak' => '5.00',
        'karbohidrat' => '47.00',
        'protein' => '13.00',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah dengan diameter 6 cm',
        'referensi_gram_berat' => '100',
    ),
    114 =>
    array (
        'id_pangan' => 115,
        'nama_pangan' => '    Alpukat',
        'gram' => '1000.00',
        'kalori' => '850.00',
        'lemak' => '65.00',
        'karbohidrat' => '77.00',
        'protein' => '9.00',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1/2 buah besar',
        'referensi_gram_berat' => '50',
    ),
    115 =>
    array (
        'id_pangan' => 116,
        'nama_pangan' => '    Jambu biji',
        'gram' => '1000.00',
        'kalori' => '490.00',
        'lemak' => '3.00',
        'karbohidrat' => '122.00',
        'protein' => '9.00',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => '1 buah besar',
        'referensi_gram_berat' => '100',
    ),
    116 =>
    array (
        'id_pangan' => 117,
        'nama_pangan' => '    Buah-buahan lainnya',
        'gram' => '1000.00',
        'kalori' => '383.98',
        'lemak' => '17.97',
        'karbohidrat' => '125.88',
        'protein' => '10.00',
        'id_jenis_pangan' => 8,
        'id_takaran' => 1,
        'referensi_urt' => 'Kg',
        'referensi_gram_berat' => ' 1,000.0 ',
    ),
    117 =>
    array (
        'id_pangan' => 118,
        'nama_pangan' => '    Minyak kelapa',
        'gram' => '800.00',
        'kalori' => '6960.00',
        'lemak' => '784.00',
        'karbohidrat' => '0.00',
        'protein' => '8.00',
        'id_jenis_pangan' => 9,
        'id_takaran' => 4,
        'referensi_urt' => '1 sendok teh',
        'referensi_gram_berat' => '4.6',
    ),
    118 =>
    array (
        'id_pangan' => 119,
    'nama_pangan' => '    Minyak goreng (kelapa sawit, bunga matahari)',
        'gram' => '800.00',
        'kalori' => '7216.00',
        'lemak' => '88.00',
        'karbohidrat' => '0.00',
        'protein' => '0.00',
        'id_jenis_pangan' => 9,
        'id_takaran' => 4,
        'referensi_urt' => '1 sendok makan',
        'referensi_gram_berat' => '10.12',
    ),
    119 =>
    array (
        'id_pangan' => 120,
    'nama_pangan' => '    Kelapa (tidak termasuk santan instan)',
        'gram' => '250.00',
        'kalori' => '1335.50',
        'lemak' => '130.12',
        'karbohidrat' => '52.10',
        'protein' => '12.65',
        'id_jenis_pangan' => 9,
        'id_takaran' => 3,
        'referensi_urt' => 'Butir',
        'referensi_gram_berat' => ' 250.0 ',
    ),
    120 =>
    array (
        'id_pangan' => 121,
        'nama_pangan' => '    Minyak dan kelapa lainnya',
        'gram' => '800.00',
        'kalori' => '6598.00',
        'lemak' => '810.00',
        'karbohidrat' => '0.00',
        'protein' => '13.50',
        'id_jenis_pangan' => 9,
        'id_takaran' => 4,
        'referensi_urt' => 'Liter',
        'referensi_gram_berat' => ' 800.0 ',
    ),
    121 =>
    array (
        'id_pangan' => 122,
        'nama_pangan' => '    Gula pasir',
        'gram' => '100.00',
        'kalori' => '364.00',
        'lemak' => '0.00',
        'karbohidrat' => '94.00',
        'protein' => '0.00',
        'id_jenis_pangan' => 10,
        'id_takaran' => 2,
        'referensi_urt' => '1 sendok makan ',
        'referensi_gram_berat' => '12.5',
    ),
    122 =>
    array (
        'id_pangan' => 123,
    'nama_pangan' => '    Gula merah, gula air (pohom aren, kelapa, lontar)',
        'gram' => '100.00',
        'kalori' => '377.00',
        'lemak' => '10.00',
        'karbohidrat' => '85.50',
        'protein' => '3.00',
        'id_jenis_pangan' => 10,
        'id_takaran' => 2,
        'referensi_urt' => '1 sendok makan ',
        'referensi_gram_berat' => '10',
    ),
    123 =>
    array (
        'id_pangan' => 124,
        'nama_pangan' => '    Teh bubuk',
        'gram' => '100.00',
        'kalori' => '132.00',
        'lemak' => '0.70',
        'karbohidrat' => '67.80',
        'protein' => '19.50',
        'id_jenis_pangan' => 10,
        'id_takaran' => 2,
        'referensi_urt' => '1 sendok makan ',
        'referensi_gram_berat' => '5.5',
    ),
    124 =>
    array (
        'id_pangan' => 125,
    'nama_pangan' => '    Teh celup (sachet)',
        'gram' => '2.00',
        'kalori' => '2.64',
        'lemak' => '0.01',
        'karbohidrat' => '1.36',
        'protein' => '0.39',
        'id_jenis_pangan' => 10,
        'id_takaran' => 15,
        'referensi_urt' => '2gr',
        'referensi_gram_berat' => ' 2.0 ',
    ),
    125 =>
    array (
        'id_pangan' => 126,
    'nama_pangan' => '    Kopi (bubuk, biji)',
        'gram' => '100.00',
        'kalori' => '352.00',
        'lemak' => '1.30',
        'karbohidrat' => '69.00',
        'protein' => '17.40',
        'id_jenis_pangan' => 10,
        'id_takaran' => 2,
        'referensi_urt' => '1 sendok makan ',
        'referensi_gram_berat' => ' 15.0 ',
    ),
    126 =>
    array (
        'id_pangan' => 127,
    'nama_pangan' => '    Kopi instan (sachet)',
        'gram' => '20.00',
        'kalori' => '90.00',
        'lemak' => '15.00',
        'karbohidrat' => '17.00',
        'protein' => '1.00',
        'id_jenis_pangan' => 10,
        'id_takaran' => 16,
        'referensi_urt' => '20gr',
        'referensi_gram_berat' => ' 20.0 ',
    ),
    127 =>
    array (
        'id_pangan' => 128,
        'nama_pangan' => '    Bahan minuman lainnya',
        'gram' => '100.00',
        'kalori' => '666.50',
        'lemak' => '0.00',
        'karbohidrat' => '0.00',
        'protein' => '8.17',
        'id_jenis_pangan' => 10,
        'id_takaran' => 2,
        'referensi_urt' => 'ons',
        'referensi_gram_berat' => ' 100.0 ',
    ),
    128 =>
    array (
        'id_pangan' => 129,
        'nama_pangan' => '    Garam',
        'gram' => '1.00',
        'kalori' => '0.00',
        'lemak' => '0.00',
        'karbohidrat' => '0.00',
        'protein' => '0.00',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 sendok teh',
        'referensi_gram_berat' => '4.2',
    ),
    129 =>
    array (
        'id_pangan' => 130,
        'nama_pangan' => '    Kemiri',
        'gram' => '1.00',
        'kalori' => '6.36',
        'lemak' => '0.63',
        'karbohidrat' => '0.08',
        'protein' => '0.19',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 biji',
        'referensi_gram_berat' => '10',
    ),
    130 =>
    array (
        'id_pangan' => 131,
        'nama_pangan' => '    Ketumbar/jinten',
        'gram' => '1.00',
        'kalori' => '4.04',
        'lemak' => '0.16',
        'karbohidrat' => '0.54',
        'protein' => '0.14',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 sendok teh',
        'referensi_gram_berat' => '5',
    ),
    131 =>
    array (
        'id_pangan' => 132,
        'nama_pangan' => '    Merica/lada',
        'gram' => '1.00',
        'kalori' => '3.59',
        'lemak' => '0.07',
        'karbohidrat' => '0.64',
        'protein' => '0.12',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 sendok teh',
        'referensi_gram_berat' => '5',
    ),
    132 =>
    array (
        'id_pangan' => 133,
        'nama_pangan' => '    Jahe',
        'gram' => '1.00',
        'kalori' => '0.51',
        'lemak' => '0.01',
        'karbohidrat' => '0.10',
        'protein' => '0.02',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 ruas jempol',
        'referensi_gram_berat' => '4',
    ),
    133 =>
    array (
        'id_pangan' => 134,
        'nama_pangan' => '    Kunyit',
        'gram' => '1.00',
        'kalori' => '0.69',
        'lemak' => '0.03',
        'karbohidrat' => '0.09',
        'protein' => '0.02',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 ruas jempol',
        'referensi_gram_berat' => '4',
    ),
    134 =>
    array (
        'id_pangan' => 135,
        'nama_pangan' => '    Asam',
        'gram' => '1.00',
        'kalori' => '1.32',
        'lemak' => '0.01',
        'karbohidrat' => '0.31',
        'protein' => '0.01',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 sendok makan',
        'referensi_gram_berat' => '15',
    ),
    135 =>
    array (
        'id_pangan' => 136,
        'nama_pangan' => '    Terasi/petis',
        'gram' => '1.00',
        'kalori' => '2.50',
        'lemak' => '0.02',
        'karbohidrat' => '0.35',
        'protein' => '0.23',
        'id_jenis_pangan' => 12,
        'id_takaran' => 5,
        'referensi_urt' => '1 sendok makan',
        'referensi_gram_berat' => '15',
    ),
    136 =>
    array (
        'id_pangan' => 137,
        'nama_pangan' => '    Kecap',
        'gram' => '100.00',
        'kalori' => '36.79',
        'lemak' => '1.04',
        'karbohidrat' => '7.20',
        'protein' => '4.56',
        'id_jenis_pangan' => 12,
        'id_takaran' => 17,
    'referensi_urt' => '100ml*)',
    'referensi_gram_berat' => ' 100.0 ',
),
137 =>
array (
    'id_pangan' => 138,
    'nama_pangan' => '    Penyedap masakan/vetsin',
    'gram' => '1.00',
    'kalori' => '0.00',
    'lemak' => '0.00',
    'karbohidrat' => '0.00',
    'protein' => '0.00',
    'id_jenis_pangan' => 12,
    'id_takaran' => 5,
    'referensi_urt' => 'Gram',
    'referensi_gram_berat' => ' 1.0 ',
),
138 =>
array (
    'id_pangan' => 139,
    'nama_pangan' => '    Sambal jadi',
    'gram' => '100.00',
    'kalori' => '78.43',
    'lemak' => '0.32',
    'karbohidrat' => '19.60',
    'protein' => '1.60',
    'id_jenis_pangan' => 12,
    'id_takaran' => 17,
'referensi_urt' => '100ml*)',
'referensi_gram_berat' => ' 100.0 ',
),
139 =>
array (
'id_pangan' => 140,
'nama_pangan' => '    Saus tomat',
'gram' => '100.00',
'kalori' => '78.43',
'lemak' => '0.32',
'karbohidrat' => '19.60',
'protein' => '1.60',
'id_jenis_pangan' => 12,
'id_takaran' => 17,
'referensi_urt' => '100ml*)',
'referensi_gram_berat' => ' 100.0 ',
),
140 =>
array (
'id_pangan' => 141,
'nama_pangan' => '    Bumbu maskan jadi/kemasan, bumbu racikan',
'gram' => '1.00',
'kalori' => '0.00',
'lemak' => '0.00',
'karbohidrat' => '0.00',
'protein' => '0.00',
'id_jenis_pangan' => 12,
'id_takaran' => 5,
'referensi_urt' => 'Gram',
'referensi_gram_berat' => ' 1.0 ',
),
141 =>
array (
'id_pangan' => 142,
'nama_pangan' => '    Bumbu dapur lainnya (pala, jahe, kunyit, dsb.)',
'gram' => '1.00',
'kalori' => '0.49',
'lemak' => '0.02',
'karbohidrat' => '0.08',
'protein' => '0.02',
'id_jenis_pangan' => 12,
'id_takaran' => 5,
'referensi_urt' => 'Gram',
'referensi_gram_berat' => ' 1.0 ',
),
142 =>
array (
'id_pangan' => 143,
'nama_pangan' => '    Mie instan',
'gram' => '80.00',
'kalori' => '356.00',
'lemak' => '13.60',
'karbohidrat' => '48.00',
'protein' => '8.00',
'id_jenis_pangan' => 13,
'id_takaran' => 18,
'referensi_urt' => '80gr**)',
'referensi_gram_berat' => ' 80.0 ',
),
143 =>
array (
'id_pangan' => 144,
'nama_pangan' => '    Kerupuk',
'gram' => '100.00',
'kalori' => '453.00',
'lemak' => '17.85',
'karbohidrat' => '69.15',
'protein' => '3.88',
'id_jenis_pangan' => 13,
'id_takaran' => 2,
'referensi_urt' => '3 biji sedang',
'referensi_gram_berat' => '30',
),
144 =>
array (
'id_pangan' => 145,
'nama_pangan' => '    Bubur bayi kemasan',
'gram' => '150.00',
'kalori' => '277.10',
'lemak' => '5.10',
'karbohidrat' => '47.84',
'protein' => '9.96',
'id_jenis_pangan' => 13,
'id_takaran' => 19,
'referensi_urt' => '150gr*)',
'referensi_gram_berat' => ' 150.0 ',
),
145 =>
array (
'id_pangan' => 146,
'nama_pangan' => '    Lainnya :',
'gram' => '100.00',
'kalori' => '396.08',
'lemak' => '2.20',
'karbohidrat' => '78.00',
'protein' => '8.50',
'id_jenis_pangan' => 13,
'id_takaran' => 5,
'referensi_urt' => 'gr',
'referensi_gram_berat' => ' 100.0 ',
),
146 =>
array (
'id_pangan' => 147,
'nama_pangan' => '    Roti tawar',
'gram' => '150.00',
'kalori' => '248.50',
'lemak' => '1.35',
'karbohidrat' => '49.85',
'protein' => '7.95',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 150.0 ',
),
147 =>
array (
'id_pangan' => 148,
'nama_pangan' => '    Roti manis, roti lainnya',
'gram' => '30.00',
'kalori' => '161.50',
'lemak' => '5.75',
'karbohidrat' => '25.05',
'protein' => '2.45',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 30.0 ',
),
148 =>
array (
'id_pangan' => 149,
'nama_pangan' => '    Kue kering, biskuit, semprong',
'gram' => '100.00',
'kalori' => '426.30',
'lemak' => '13.02',
'karbohidrat' => '72.24',
'protein' => '6.19',
'id_jenis_pangan' => 14,
'id_takaran' => 2,
'referensi_urt' => 'Ons',
'referensi_gram_berat' => ' 100.0 ',
),
149 =>
array (
'id_pangan' => 150,
'nama_pangan' => '    Kue basah (kue lapis, bika ambon, lemper, dsb)',
'gram' => '30.00',
'kalori' => '137.50',
'lemak' => '2.91',
'karbohidrat' => '25.91',
'protein' => '1.96',
'id_jenis_pangan' => 14,
'id_takaran' => 7,
'referensi_urt' => 'Buah',
'referensi_gram_berat' => ' 30.0 ',
),
150 =>
array (
'id_pangan' => 151,
'nama_pangan' => '    Makanan gorengan (tahu, tempe, bakwan, pisang)',
'gram' => '40.00',
'kalori' => '94.30',
'lemak' => '6.16',
'karbohidrat' => '7.06',
'protein' => '3.62',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 40.0 ',
),
151 =>
array (
'id_pangan' => 152,
'nama_pangan' => '    Makanan gorengan lainnya',
'gram' => '40.00',
'kalori' => '181.00',
'lemak' => '10.35',
'karbohidrat' => '18.02',
'protein' => '4.94',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 40.0 ',
),
152 =>
array (
'id_pangan' => 153,
'nama_pangan' => '    Bubur kacang hijau',
'gram' => '200.00',
'kalori' => '109.00',
'lemak' => '0.50',
'karbohidrat' => '18.30',
'protein' => '8.70',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 200.0 ',
),
153 =>
array (
'id_pangan' => 154,
'nama_pangan' => '    Gado-gado, ketoprak, pecel',
'gram' => '250.00',
'kalori' => '290.00',
'lemak' => '10.90',
'karbohidrat' => '34.00',
'protein' => '14.00',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 250.0 ',
),
154 =>
array (
'id_pangan' => 155,
'nama_pangan' => '    Nasi campur/rames',
'gram' => '500.00',
'kalori' => '583.60',
'lemak' => '9.07',
'karbohidrat' => '103.62',
'protein' => '19.42',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 500.0 ',
),
155 =>
array (
'id_pangan' => 156,
'nama_pangan' => '    Nasi goreng',
'gram' => '250.00',
'kalori' => '552.00',
'lemak' => '6.40',
'karbohidrat' => '60.40',
'protein' => '6.40',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 250.0 ',
),
156 =>
array (
'id_pangan' => 157,
'nama_pangan' => '    Nasi putih',
'gram' => '200.00',
'kalori' => '391.60',
'lemak' => '0.22',
'karbohidrat' => '89.32',
'protein' => '4.62',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 200.0 ',
),
157 =>
array (
'id_pangan' => 158,
'nama_pangan' => '    Lontong/ketupat sayur',
'gram' => '350.00',
'kalori' => '263.80',
'lemak' => '5.20',
'karbohidrat' => '47.00',
'protein' => '5.93',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 350.0 ',
),
158 =>
array (
'id_pangan' => 159,
'nama_pangan' => '    Soto, gule, sop, rawon, cincang',
'gram' => '250.00',
'kalori' => '143.70',
'lemak' => '7.96',
'karbohidrat' => '9.11',
'protein' => '8.92',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 250.0 ',
),
159 =>
array (
'id_pangan' => 160,
'nama_pangan' => '    Sayur matang (ditumis, disantan, dsb)',
'gram' => '250.00',
'kalori' => '232.50',
'lemak' => '8.02',
'karbohidrat' => '30.04',
'protein' => '9.62',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 250.0 ',
),
160 =>
array (
'id_pangan' => 161,
'nama_pangan' => '    Sate, tongseng',
'gram' => '25.00',
'kalori' => '89.50',
'lemak' => '1.75',
'karbohidrat' => '6.65',
'protein' => '11.25',
'id_jenis_pangan' => 14,
'id_takaran' => 20,
'referensi_urt' => 'Porsi/5 tusuk',
'referensi_gram_berat' => ' 25.0 ',
),
161 =>
array (
'id_pangan' => 162,
'nama_pangan' => '    Mie bakso, mie rebus, mie goreng',
'gram' => '250.00',
'kalori' => '529.00',
'lemak' => '22.10',
'karbohidrat' => '70.80',
'protein' => '6.82',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 250.0 ',
),
162 =>
array (
'id_pangan' => 163,
'nama_pangan' => '    Mie instan',
'gram' => '250.00',
'kalori' => '356.00',
'lemak' => '13.60',
'karbohidrat' => '48.00',
'protein' => '8.00',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 250.0 ',
),
163 =>
array (
'id_pangan' => 164,
'nama_pangan' => '    Makanan ringan anak-anak, krupuk/kripik',
'gram' => '100.00',
'kalori' => '509.10',
'lemak' => '23.32',
'karbohidrat' => '60.40',
'protein' => '6.28',
'id_jenis_pangan' => 14,
'id_takaran' => 2,
'referensi_urt' => 'Ons',
'referensi_gram_berat' => ' 100.0 ',
),
164 =>
array (
'id_pangan' => 165,
'nama_pangan' => '    Ikan matang',
'gram' => '75.00',
'kalori' => '624.00',
'lemak' => '35.85',
'karbohidrat' => '0.00',
'protein' => '70.35',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 75.0 ',
),
165 =>
array (
'id_pangan' => 166,
'nama_pangan' => '    Ayam/bebek/daging matang (ayam goreng, rendang, dsb)',
'gram' => '150.00',
'kalori' => '490.00',
'lemak' => '22.80',
'karbohidrat' => '0.60',
'protein' => '66.20',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 150.0 ',
),
166 =>
array (
'id_pangan' => 167,
'nama_pangan' => '    Daging olahan (sosis, nugget, daging asap, dsb) matang',
'gram' => '100.00',
'kalori' => '340.00',
'lemak' => '3.55',
'karbohidrat' => '1.10',
'protein' => '11.05',
'id_jenis_pangan' => 14,
'id_takaran' => 6,
'referensi_urt' => 'Potong',
'referensi_gram_berat' => ' 100.0 ',
),
167 =>
array (
'id_pangan' => 168,
'nama_pangan' => '    Bubur ayam',
'gram' => '125.00',
'kalori' => '203.75',
'lemak' => '6.58',
'karbohidrat' => '28.06',
'protein' => '7.43',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 125.0 ',
),
168 =>
array (
'id_pangan' => 169,
'nama_pangan' => '    Siomay, batagor',
'gram' => '125.00',
'kalori' => '203.75',
'lemak' => '6.58',
'karbohidrat' => '28.06',
'protein' => '7.43',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 125.0 ',
),
169 =>
array (
'id_pangan' => 170,
'nama_pangan' => '    Makanan jadi lainnya',
'gram' => '30.00',
'kalori' => '246.30',
'lemak' => '11.29',
'karbohidrat' => '24.20',
'protein' => '8.90',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 30.0 ',
),
170 =>
array (
'id_pangan' => 171,
'nama_pangan' => '    Air kemasan',
'gram' => '520.00',
'kalori' => '0.00',
'lemak' => '0.00',
'karbohidrat' => '0.00',
'protein' => '0.00',
'id_jenis_pangan' => 14,
'id_takaran' => 4,
'referensi_urt' => 'Liter',
'referensi_gram_berat' => ' 520.0 ',
),
171 =>
array (
'id_pangan' => 172,
'nama_pangan' => '    Air kemasan galon',
'gram' => '1000.00',
'kalori' => '0.00',
'lemak' => '0.00',
'karbohidrat' => '0.00',
'protein' => '0.00',
'id_jenis_pangan' => 14,
'id_takaran' => 9,
'referensi_urt' => 'Galon',
'referensi_gram_berat' => ' 1,000.0 ',
),
172 =>
array (
'id_pangan' => 173,
'nama_pangan' => '    Air teh kemasan, minuman bersoda/mengandung CO2',
'gram' => '200.00',
'kalori' => '68.13',
'lemak' => '0.00',
'karbohidrat' => '0.00',
'protein' => '0.00',
'id_jenis_pangan' => 14,
'id_takaran' => 12,
'referensi_urt' => '250ml*)',
'referensi_gram_berat' => ' 200.0 ',
),
173 =>
array (
'id_pangan' => 174,
'nama_pangan' => '    Sari buah kemasan, minuman kesehatan, minuman berenergi',
'gram' => '160.00',
'kalori' => '72.53',
'lemak' => '0.00',
'karbohidrat' => '0.00',
'protein' => '0.00',
'id_jenis_pangan' => 14,
'id_takaran' => 21,
'referensi_urt' => '200ml*)',
'referensi_gram_berat' => ' 160.0 ',
),
174 =>
array (
'id_pangan' => 175,
'nama_pangan' => '    Minuman jadi(kopi, kopi susu, teh, susu coklat, dsb)',
'gram' => '208.00',
'kalori' => '61.00',
'lemak' => '3.50',
'karbohidrat' => '4.30',
'protein' => '3.20',
'id_jenis_pangan' => 14,
'id_takaran' => 10,
'referensi_urt' => 'Gelas',
'referensi_gram_berat' => ' 208.0 ',
),
175 =>
array (
'id_pangan' => 176,
'nama_pangan' => '    Es krim',
'gram' => '50.00',
'kalori' => '207.00',
'lemak' => '12.50',
'karbohidrat' => '20.60',
'protein' => '4.00',
'id_jenis_pangan' => 14,
'id_takaran' => 11,
'referensi_urt' => 'Mangkok kecil',
'referensi_gram_berat' => ' 50.0 ',
),
176 =>
array (
'id_pangan' => 177,
'nama_pangan' => '    Es lainnya',
'gram' => '200.00',
'kalori' => '56.00',
'lemak' => '0.00',
'karbohidrat' => '14.10',
'protein' => '0.00',
'id_jenis_pangan' => 14,
'id_takaran' => 8,
'referensi_urt' => 'Porsi',
'referensi_gram_berat' => ' 200.0 ',
),
177 =>
array (
'id_pangan' => 178,
'nama_pangan' => '    Minuman keras',
'gram' => '800.00',
'kalori' => '384.00',
'lemak' => '0.00',
'karbohidrat' => '35.19',
'protein' => '4.81',
'id_jenis_pangan' => 14,
'id_takaran' => 4,
'referensi_urt' => 'Liter',
'referensi_gram_berat' => ' 800.0',
),
));


    }
}
