<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PanganTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pangan')->delete();
        
        \DB::table('pangan')->insert(array (
            0 => 
            array (
                'idpangan' => 1,
                'nama_pangan' => 'Nasi',
                'takaran' => 'entong',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '178.00',
                'lemak' => '0.10',
                'karbohidrat' => '40.60',
                'protein' => '2.10',
                'idjenis_pangan' => 1,
            ),
            1 => 
            array (
                'idpangan' => 2,
                'nama_pangan' => 'Nasi Jagung',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '133.33',
                'kalori' => '233.33',
                'lemak' => '0.00',
                'karbohidrat' => '53.33',
                'protein' => '5.33',
                'idjenis_pangan' => 1,
            ),
            2 => 
            array (
                'idpangan' => 3,
                'nama_pangan' => 'Singkong',
                'takaran' => 'Potong',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '175.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '4.00',
                'idjenis_pangan' => 2,
            ),
            3 => 
            array (
                'idpangan' => 4,
                'nama_pangan' => 'Beras Singkong',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '175.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '4.00',
                'idjenis_pangan' => 2,
            ),
            4 => 
            array (
                'idpangan' => 5,
                'nama_pangan' => 'Tiwul',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '350.00',
                'lemak' => '0.00',
                'karbohidrat' => '80.00',
                'protein' => '8.00',
                'idjenis_pangan' => 2,
            ),
            5 => 
            array (
                'idpangan' => 6,
                'nama_pangan' => 'Tiwul Kukus',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '175.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '4.00',
                'idjenis_pangan' => 2,
            ),
            6 => 
            array (
                'idpangan' => 7,
                'nama_pangan' => 'Kentang',
                'takaran' => 'Biji Sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '87.50',
                'lemak' => '0.00',
                'karbohidrat' => '20.00',
                'protein' => '2.00',
                'idjenis_pangan' => 2,
            ),
            7 => 
            array (
                'idpangan' => 8,
                'nama_pangan' => 'Talas',
                'takaran' => 'Biji Sedang',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '175.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '4.00',
                'idjenis_pangan' => 2,
            ),
            8 => 
            array (
                'idpangan' => 9,
                'nama_pangan' => 'Ubi jalar',
                'takaran' => 'Biji Sedang',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '175.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '4.00',
                'idjenis_pangan' => 2,
            ),
            9 => 
            array (
                'idpangan' => 10,
                'nama_pangan' => 'Mie bendo / singkong',
                'takaran' => 'Piring Sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '175.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '4.00',
                'idjenis_pangan' => 2,
            ),
            10 => 
            array (
                'idpangan' => 11,
                'nama_pangan' => 'Beras',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '540.00',
                'lemak' => '1.05',
                'karbohidrat' => '118.35',
                'protein' => '10.20',
                'idjenis_pangan' => 1,
            ),
            11 => 
            array (
                'idpangan' => 12,
                'nama_pangan' => 'Hotong',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '525.00',
                'lemak' => '0.00',
                'karbohidrat' => '120.00',
                'protein' => '12.00',
                'idjenis_pangan' => 1,
            ),
            12 => 
            array (
                'idpangan' => 13,
                'nama_pangan' => 'Jali',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '180.00',
                'kalori' => '525.00',
                'lemak' => '0.00',
                'karbohidrat' => '120.00',
                'protein' => '12.00',
                'idjenis_pangan' => 1,
            ),
            13 => 
            array (
                'idpangan' => 14,
                'nama_pangan' => 'Jewawut',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '350.00',
                'lemak' => '0.00',
                'karbohidrat' => '80.00',
                'protein' => '8.00',
                'idjenis_pangan' => 1,
            ),
            14 => 
            array (
                'idpangan' => 15,
                'nama_pangan' => 'Meisena',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '21.88',
                'lemak' => '0.00',
                'karbohidrat' => '0.50',
                'protein' => '5.00',
                'idjenis_pangan' => 2,
            ),
            15 => 
            array (
                'idpangan' => 16,
                'nama_pangan' => 'Tepung sagu',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '5.71',
                'kalori' => '25.00',
                'lemak' => '0.00',
                'karbohidrat' => '0.57',
                'protein' => '5.71',
                'idjenis_pangan' => 2,
            ),
            16 => 
            array (
                'idpangan' => 17,
                'nama_pangan' => 'Tepung singkong',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '6.25',
                'kalori' => '21.88',
                'lemak' => '0.00',
                'karbohidrat' => '0.50',
                'protein' => '5.00',
                'idjenis_pangan' => 2,
            ),
            17 => 
            array (
                'idpangan' => 18,
                'nama_pangan' => 'Daging',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            18 => 
            array (
                'idpangan' => 19,
                'nama_pangan' => 'Babat',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '30.00',
                'kalori' => '47.50',
                'lemak' => '3.00',
                'karbohidrat' => '0.00',
                'protein' => '2.00',
                'idjenis_pangan' => 3,
            ),
            19 => 
            array (
                'idpangan' => 20,
            'nama_pangan' => 'Bakso daging(kecil)',
                'takaran' => 'Biji Kecil',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '4.75',
                'lemak' => '0.30',
                'karbohidrat' => '0.00',
                'protein' => '0.20',
                'idjenis_pangan' => 3,
            ),
            20 => 
            array (
                'idpangan' => 21,
            'nama_pangan' => 'Bakso daging(Sedang)',
                'takaran' => 'Biji Sedang',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '9.50',
                'lemak' => '0.60',
                'karbohidrat' => '0.00',
                'protein' => '0.40',
                'idjenis_pangan' => 3,
            ),
            21 => 
            array (
                'idpangan' => 22,
                'nama_pangan' => 'Daging Ayam',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            22 => 
            array (
                'idpangan' => 23,
                'nama_pangan' => 'Daging sapi',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            23 => 
            array (
                'idpangan' => 24,
                'nama_pangan' => 'Hati sapi',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            24 => 
            array (
                'idpangan' => 25,
                'nama_pangan' => 'Ikan asin',
                'takaran' => 'Potong Kecil',
                'urt' => 1,
                'gram' => '25.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            25 => 
            array (
                'idpangan' => 26,
                'nama_pangan' => 'Dadih sapi',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '12.50',
                'kalori' => '47.50',
                'lemak' => '3.00',
                'karbohidrat' => '0.00',
                'protein' => '2.00',
                'idjenis_pangan' => 3,
            ),
            26 => 
            array (
                'idpangan' => 27,
                'nama_pangan' => 'Usus Sapi',
                'takaran' => 'Bulatan',
                'urt' => 1,
                'gram' => '25.00',
                'kalori' => '31.67',
                'lemak' => '2.00',
                'karbohidrat' => '0.00',
                'protein' => '1.33',
                'idjenis_pangan' => 3,
            ),
            27 => 
            array (
                'idpangan' => 28,
                'nama_pangan' => 'Ikan segar',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            28 => 
            array (
                'idpangan' => 29,
                'nama_pangan' => 'Ikan teri',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '12.50',
                'kalori' => '47.50',
                'lemak' => '3.00',
                'karbohidrat' => '0.00',
                'protein' => '2.00',
                'idjenis_pangan' => 3,
            ),
            29 => 
            array (
                'idpangan' => 30,
                'nama_pangan' => 'Daging Burger',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '29.25',
                'kalori' => '23.75',
                'lemak' => '1.50',
                'karbohidrat' => '0.00',
                'protein' => '1.00',
                'idjenis_pangan' => 3,
            ),
            30 => 
            array (
                'idpangan' => 31,
                'nama_pangan' => 'Keju',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '30.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            31 => 
            array (
                'idpangan' => 32,
                'nama_pangan' => 'Telur ayam',
                'takaran' => 'Butir',
                'urt' => 1,
                'gram' => '30.00',
                'kalori' => '47.50',
                'lemak' => '3.00',
                'karbohidrat' => '0.00',
                'protein' => '2.00',
                'idjenis_pangan' => 3,
            ),
            32 => 
            array (
                'idpangan' => 33,
                'nama_pangan' => 'Telur ayam negri',
                'takaran' => 'Butir',
                'urt' => 1,
                'gram' => '60.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            33 => 
            array (
                'idpangan' => 34,
                'nama_pangan' => 'Telur bebek',
                'takaran' => 'Butir',
                'urt' => 1,
                'gram' => '60.00',
                'kalori' => '95.00',
                'lemak' => '6.00',
                'karbohidrat' => '0.00',
                'protein' => '4.00',
                'idjenis_pangan' => 3,
            ),
            34 => 
            array (
                'idpangan' => 35,
                'nama_pangan' => 'Telur puyuh',
                'takaran' => 'Butir',
                'urt' => 1,
                'gram' => '12.00',
                'kalori' => '19.00',
                'lemak' => '1.20',
                'karbohidrat' => '0.00',
                'protein' => '0.80',
                'idjenis_pangan' => 3,
            ),
            35 => 
            array (
                'idpangan' => 36,
                'nama_pangan' => 'Udang basah',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '380.00',
                'lemak' => '24.00',
                'karbohidrat' => '0.00',
                'protein' => '16.00',
                'idjenis_pangan' => 3,
            ),
            36 => 
            array (
                'idpangan' => 37,
                'nama_pangan' => 'Rolade',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '40.00',
                'kalori' => '19.00',
                'lemak' => '1.20',
                'karbohidrat' => '0.00',
                'protein' => '0.80',
                'idjenis_pangan' => 3,
            ),
            37 => 
            array (
                'idpangan' => 38,
                'nama_pangan' => 'Sosis',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '27.67',
                'kalori' => '31.67',
                'lemak' => '2.00',
                'karbohidrat' => '0.00',
                'protein' => '1.33',
                'idjenis_pangan' => 3,
            ),
            38 => 
            array (
                'idpangan' => 39,
                'nama_pangan' => 'Nugget ayam',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '16.60',
                'kalori' => '19.00',
                'lemak' => '1.20',
                'karbohidrat' => '0.00',
                'protein' => '0.80',
                'idjenis_pangan' => 3,
            ),
            39 => 
            array (
                'idpangan' => 40,
                'nama_pangan' => 'Bakso Udang',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '11.67',
                'kalori' => '6.33',
                'lemak' => '0.40',
                'karbohidrat' => '0.00',
                'protein' => '0.27',
                'idjenis_pangan' => 3,
            ),
            40 => 
            array (
                'idpangan' => 41,
                'nama_pangan' => 'Abon sapi',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '20.83',
                'kalori' => '31.67',
                'lemak' => '2.00',
                'karbohidrat' => '0.00',
                'protein' => '1.33',
                'idjenis_pangan' => 3,
            ),
            41 => 
            array (
                'idpangan' => 42,
                'nama_pangan' => 'Tempe',
                'takaran' => 'Potong',
                'urt' => 1,
                'gram' => '25.00',
                'kalori' => '82.00',
                'lemak' => '5.80',
                'karbohidrat' => '3.20',
                'protein' => '4.60',
                'idjenis_pangan' => 6,
            ),
            42 => 
            array (
                'idpangan' => 43,
                'nama_pangan' => 'Kacang hijau',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '32.00',
                'lemak' => '1.20',
                'karbohidrat' => '3.20',
                'protein' => '2.40',
                'idjenis_pangan' => 6,
            ),
            43 => 
            array (
                'idpangan' => 44,
                'nama_pangan' => 'Kacang kedele',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '32.00',
                'lemak' => '1.20',
                'karbohidrat' => '3.20',
                'protein' => '2.40',
                'idjenis_pangan' => 6,
            ),
            44 => 
            array (
                'idpangan' => 45,
                'nama_pangan' => 'Kacang merah',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '32.00',
                'lemak' => '1.20',
                'karbohidrat' => '3.20',
                'protein' => '2.40',
                'idjenis_pangan' => 6,
            ),
            45 => 
            array (
                'idpangan' => 46,
                'nama_pangan' => 'Oncom',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '25.00',
                'kalori' => '40.00',
                'lemak' => '1.50',
                'karbohidrat' => '4.00',
                'protein' => '3.00',
                'idjenis_pangan' => 5,
            ),
            46 => 
            array (
                'idpangan' => 47,
                'nama_pangan' => 'Kacang tanah',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '40.00',
                'lemak' => '1.50',
                'karbohidrat' => '4.00',
                'protein' => '3.00',
                'idjenis_pangan' => 6,
            ),
            47 => 
            array (
                'idpangan' => 48,
                'nama_pangan' => 'Keju kc tanah',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '40.00',
                'lemak' => '1.50',
                'karbohidrat' => '4.00',
                'protein' => '3.00',
                'idjenis_pangan' => 6,
            ),
            48 => 
            array (
                'idpangan' => 49,
                'nama_pangan' => 'Kacang tolo',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '32.00',
                'lemak' => '1.20',
                'karbohidrat' => '3.20',
                'protein' => '2.40',
                'idjenis_pangan' => 6,
            ),
            49 => 
            array (
                'idpangan' => 50,
                'nama_pangan' => 'Tahu',
                'takaran' => 'Biji Besar',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '80.00',
                'lemak' => '3.00',
                'karbohidrat' => '8.00',
                'protein' => '6.00',
                'idjenis_pangan' => 5,
            ),
            50 => 
            array (
                'idpangan' => 51,
                'nama_pangan' => 'Baligo',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            51 => 
            array (
                'idpangan' => 52,
                'nama_pangan' => 'Labu air',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            52 => 
            array (
                'idpangan' => 53,
                'nama_pangan' => 'Daun koro',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            53 => 
            array (
                'idpangan' => 54,
                'nama_pangan' => 'Daun labu siam',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            54 => 
            array (
                'idpangan' => 55,
                'nama_pangan' => 'Daun waluh',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            55 => 
            array (
                'idpangan' => 56,
                'nama_pangan' => 'Daun lobak',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            56 => 
            array (
                'idpangan' => 57,
                'nama_pangan' => 'Jamur segar',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            57 => 
            array (
                'idpangan' => 58,
                'nama_pangan' => 'Seledri',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            58 => 
            array (
                'idpangan' => 59,
                'nama_pangan' => 'Taoge',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            59 => 
            array (
                'idpangan' => 60,
                'nama_pangan' => 'Kembang kol',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            60 => 
            array (
                'idpangan' => 61,
                'nama_pangan' => 'Daun kacang panjang',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            61 => 
            array (
                'idpangan' => 62,
                'nama_pangan' => 'Oyong',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            62 => 
            array (
                'idpangan' => 63,
                'nama_pangan' => 'Kangkung',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            63 => 
            array (
                'idpangan' => 64,
                'nama_pangan' => 'Timun',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            64 => 
            array (
                'idpangan' => 65,
                'nama_pangan' => 'Tomat',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '5.00',
                'protein' => '1.50',
                'idjenis_pangan' => 8,
            ),
            65 => 
            array (
                'idpangan' => 66,
                'nama_pangan' => 'Kecipir',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            66 => 
            array (
                'idpangan' => 67,
                'nama_pangan' => 'Tebu terubuk',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            67 => 
            array (
                'idpangan' => 68,
                'nama_pangan' => 'Cabe hijau besar',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            68 => 
            array (
                'idpangan' => 69,
                'nama_pangan' => 'Daun bawang',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            69 => 
            array (
                'idpangan' => 70,
                'nama_pangan' => 'Lobak',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            70 => 
            array (
                'idpangan' => 71,
                'nama_pangan' => 'Kol',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            71 => 
            array (
                'idpangan' => 72,
                'nama_pangan' => 'Pepaya muda',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            72 => 
            array (
                'idpangan' => 73,
                'nama_pangan' => 'Petai',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            73 => 
            array (
                'idpangan' => 74,
                'nama_pangan' => 'Sawi',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            74 => 
            array (
                'idpangan' => 75,
                'nama_pangan' => 'Selada',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            75 => 
            array (
                'idpangan' => 76,
                'nama_pangan' => 'Terong',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            76 => 
            array (
                'idpangan' => 77,
                'nama_pangan' => 'Bayam',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            77 => 
            array (
                'idpangan' => 78,
                'nama_pangan' => 'Biet',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            78 => 
            array (
                'idpangan' => 79,
                'nama_pangan' => 'Buncis',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            79 => 
            array (
                'idpangan' => 80,
                'nama_pangan' => 'Daun beluntas',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            80 => 
            array (
                'idpangan' => 81,
                'nama_pangan' => 'Daun ubi jalar',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            81 => 
            array (
                'idpangan' => 82,
                'nama_pangan' => 'Daun leunca',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            82 => 
            array (
                'idpangan' => 83,
                'nama_pangan' => 'Daun pepaya',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            83 => 
            array (
                'idpangan' => 84,
                'nama_pangan' => 'Daun lompong',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            84 => 
            array (
                'idpangan' => 85,
                'nama_pangan' => 'Daun mengkokan',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            85 => 
            array (
                'idpangan' => 86,
                'nama_pangan' => 'Daun melinjo',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            86 => 
            array (
                'idpangan' => 87,
                'nama_pangan' => 'Daun pakis',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            87 => 
            array (
                'idpangan' => 88,
                'nama_pangan' => 'Daun singkong',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            88 => 
            array (
                'idpangan' => 89,
                'nama_pangan' => 'Jagung muda',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            89 => 
            array (
                'idpangan' => 90,
                'nama_pangan' => 'Jagung pisang',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            90 => 
            array (
                'idpangan' => 91,
                'nama_pangan' => 'Genjer',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            91 => 
            array (
                'idpangan' => 92,
                'nama_pangan' => 'Kacang panjang',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            92 => 
            array (
                'idpangan' => 93,
                'nama_pangan' => 'Kacang kapri',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 6,
            ),
            93 => 
            array (
                'idpangan' => 94,
                'nama_pangan' => 'Kangkung',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            94 => 
            array (
                'idpangan' => 95,
                'nama_pangan' => 'Katuk',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            95 => 
            array (
                'idpangan' => 96,
                'nama_pangan' => 'Kucai',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            96 => 
            array (
                'idpangan' => 97,
                'nama_pangan' => 'Wortel',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            97 => 
            array (
                'idpangan' => 98,
                'nama_pangan' => 'Labu siam',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            98 => 
            array (
                'idpangan' => 99,
                'nama_pangan' => 'Labu waluh',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            99 => 
            array (
                'idpangan' => 100,
                'nama_pangan' => 'Nangka muda',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            100 => 
            array (
                'idpangan' => 101,
                'nama_pangan' => 'Pare',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            101 => 
            array (
                'idpangan' => 102,
                'nama_pangan' => 'Takokak',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            102 => 
            array (
                'idpangan' => 103,
                'nama_pangan' => 'Pisang ambon',
                'takaran' => 'Potong sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            103 => 
            array (
                'idpangan' => 104,
                'nama_pangan' => 'Alpukat',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '80.00',
                'lemak' => '0.00',
                'karbohidrat' => '20.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            104 => 
            array (
                'idpangan' => 105,
                'nama_pangan' => 'Anggur',
                'takaran' => 'Biji',
                'urt' => 1,
                'gram' => '7.50',
                'kalori' => '4.00',
                'lemak' => '0.00',
                'karbohidrat' => '1.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            105 => 
            array (
                'idpangan' => 106,
                'nama_pangan' => 'Apel',
                'takaran' => 'Buah sedang',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '80.00',
                'lemak' => '0.00',
                'karbohidrat' => '20.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            106 => 
            array (
                'idpangan' => 107,
                'nama_pangan' => 'Belimbing',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '125.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            107 => 
            array (
                'idpangan' => 108,
                'nama_pangan' => 'Duku',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '2.67',
                'lemak' => '0.00',
                'karbohidrat' => '0.67',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            108 => 
            array (
                'idpangan' => 109,
                'nama_pangan' => 'Jambu air',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '20.00',
                'lemak' => '0.00',
                'karbohidrat' => '5.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            109 => 
            array (
                'idpangan' => 110,
                'nama_pangan' => 'Jambu biji',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            110 => 
            array (
                'idpangan' => 111,
                'nama_pangan' => 'Jambu bol',
                'takaran' => 'Buah sedang',
                'urt' => 1,
                'gram' => '300.00',
                'kalori' => '160.00',
                'lemak' => '0.00',
                'karbohidrat' => '40.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            111 => 
            array (
                'idpangan' => 112,
                'nama_pangan' => 'Jeruk manis',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '20.00',
                'lemak' => '0.00',
                'karbohidrat' => '5.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            112 => 
            array (
                'idpangan' => 113,
                'nama_pangan' => 'Kedondong',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            113 => 
            array (
                'idpangan' => 114,
                'nama_pangan' => 'Kemang',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            114 => 
            array (
                'idpangan' => 115,
                'nama_pangan' => 'Sawo',
                'takaran' => 'Buah sedang',
                'urt' => 1,
                'gram' => '50.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            115 => 
            array (
                'idpangan' => 116,
                'nama_pangan' => 'Mangga',
                'takaran' => 'buah besar',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '80.00',
                'lemak' => '0.00',
                'karbohidrat' => '20.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            116 => 
            array (
                'idpangan' => 117,
                'nama_pangan' => 'Melon',
                'takaran' => 'Potong besar',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            117 => 
            array (
                'idpangan' => 118,
                'nama_pangan' => 'Nangka masak',
                'takaran' => 'Biji',
                'urt' => 1,
                'gram' => '16.67',
                'kalori' => '13.33',
                'lemak' => '0.00',
                'karbohidrat' => '3.33',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            118 => 
            array (
                'idpangan' => 119,
                'nama_pangan' => 'Nanas',
                'takaran' => 'Buah Besar',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '80.00',
                'lemak' => '0.00',
                'karbohidrat' => '20.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            119 => 
            array (
                'idpangan' => 120,
                'nama_pangan' => 'Pepaya',
                'takaran' => 'Potong sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            120 => 
            array (
                'idpangan' => 121,
                'nama_pangan' => 'Pisang raja sereh',
                'takaran' => 'Buah sedang',
                'urt' => 1,
                'gram' => '25.00',
                'kalori' => '20.00',
                'lemak' => '0.00',
                'karbohidrat' => '5.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            121 => 
            array (
                'idpangan' => 122,
                'nama_pangan' => 'Rambutan',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '9.38',
                'kalori' => '5.00',
                'lemak' => '0.00',
                'karbohidrat' => '1.25',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            122 => 
            array (
                'idpangan' => 123,
                'nama_pangan' => 'Salak',
                'takaran' => 'Buah besar',
                'urt' => 1,
                'gram' => '75.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            123 => 
            array (
                'idpangan' => 124,
                'nama_pangan' => 'Semangka',
                'takaran' => 'Potong Besar',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '40.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            124 => 
            array (
                'idpangan' => 125,
                'nama_pangan' => 'Sirsak',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '150.00',
                'kalori' => '80.00',
                'lemak' => '0.00',
                'karbohidrat' => '20.00',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            125 => 
            array (
                'idpangan' => 126,
                'nama_pangan' => 'Susu sapi',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '139.00',
                'lemak' => '7.00',
                'karbohidrat' => '9.00',
                'protein' => '7.00',
                'idjenis_pangan' => 7,
            ),
            126 => 
            array (
                'idpangan' => 127,
                'nama_pangan' => 'Susu kambing',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '600.00',
                'kalori' => '556.00',
                'lemak' => '28.00',
                'karbohidrat' => '36.00',
                'protein' => '28.00',
                'idjenis_pangan' => 7,
            ),
            127 => 
            array (
                'idpangan' => 128,
                'nama_pangan' => 'Susu kental tak manis',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '278.00',
                'lemak' => '14.00',
                'karbohidrat' => '18.00',
                'protein' => '14.00',
                'idjenis_pangan' => 7,
            ),
            128 => 
            array (
                'idpangan' => 129,
                'nama_pangan' => 'Susu kerbau',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '278.00',
                'lemak' => '14.00',
                'karbohidrat' => '18.00',
                'protein' => '14.00',
                'idjenis_pangan' => 7,
            ),
            129 => 
            array (
                'idpangan' => 130,
                'nama_pangan' => 'Yogurt',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '139.00',
                'lemak' => '7.00',
                'karbohidrat' => '9.00',
                'protein' => '7.00',
                'idjenis_pangan' => 7,
            ),
            130 => 
            array (
                'idpangan' => 131,
                'nama_pangan' => 'Tepung sari dele',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '6.25',
                'kalori' => '34.75',
                'lemak' => '1.75',
                'karbohidrat' => '2.25',
                'protein' => '1.75',
                'idjenis_pangan' => 7,
            ),
            131 => 
            array (
                'idpangan' => 132,
                'nama_pangan' => 'Tepung susu skim',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '34.75',
                'lemak' => '1.75',
                'karbohidrat' => '2.25',
                'protein' => '1.75',
                'idjenis_pangan' => 7,
            ),
            132 => 
            array (
                'idpangan' => 133,
                'nama_pangan' => 'Tepung susu whole',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '27.80',
                'lemak' => '1.40',
                'karbohidrat' => '1.80',
                'protein' => '1.40',
                'idjenis_pangan' => 7,
            ),
            133 => 
            array (
                'idpangan' => 134,
                'nama_pangan' => 'Minyak goreng',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '90.00',
                'lemak' => '10.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            134 => 
            array (
                'idpangan' => 135,
                'nama_pangan' => 'Minyak kelapa',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '90.00',
                'lemak' => '10.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            135 => 
            array (
                'idpangan' => 136,
                'nama_pangan' => 'Margarin',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '90.00',
                'lemak' => '10.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            136 => 
            array (
                'idpangan' => 137,
                'nama_pangan' => 'Kelapa',
                'takaran' => 'Potong Kecil',
                'urt' => 1,
                'gram' => '30.00',
                'kalori' => '45.00',
                'lemak' => '5.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            137 => 
            array (
                'idpangan' => 138,
                'nama_pangan' => 'Kelapa parut',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '6.00',
                'kalori' => '9.00',
                'lemak' => '1.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            138 => 
            array (
                'idpangan' => 139,
                'nama_pangan' => 'Santan',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '90.00',
                'lemak' => '10.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            139 => 
            array (
                'idpangan' => 140,
                'nama_pangan' => 'Minyak ikan',
                'takaran' => 'Sendok Makan',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '90.00',
                'lemak' => '10.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            140 => 
            array (
                'idpangan' => 141,
                'nama_pangan' => 'Lemak babi',
                'takaran' => 'Potong Kecil',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '45.00',
                'lemak' => '5.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            141 => 
            array (
                'idpangan' => 142,
                'nama_pangan' => 'Lemak sapi',
                'takaran' => 'Potong Kecil',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '45.00',
                'lemak' => '5.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 4,
            ),
            142 => 
            array (
                'idpangan' => 143,
                'nama_pangan' => 'Daun talas',
            'takaran' => 'Gelas (setelah dimasak dan tiriskan)',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            143 => 
            array (
                'idpangan' => 144,
                'nama_pangan' => 'Jantung pisang',
            'takaran' => 'Gelas (setelah dimasak dan tiriskan)',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            144 => 
            array (
                'idpangan' => 145,
                'nama_pangan' => 'Pecay',
            'takaran' => 'Gelas (setelah dimasak dan tiriskan)',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            145 => 
            array (
                'idpangan' => 146,
                'nama_pangan' => 'Rebung',
            'takaran' => 'Gelas (setelah dimasak dan tiriskan)',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            146 => 
            array (
                'idpangan' => 147,
                'nama_pangan' => 'Tekokak',
            'takaran' => 'Gelas (setelah dimasak dan tiriskan)',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '50.00',
                'lemak' => '0.00',
                'karbohidrat' => '10.00',
                'protein' => '3.00',
                'idjenis_pangan' => 8,
            ),
            147 => 
            array (
                'idpangan' => 148,
                'nama_pangan' => 'Gula',
                'takaran' => 'sdm',
                'urt' => 1,
                'gram' => '8.00',
                'kalori' => '30.00',
                'lemak' => '0.00',
                'karbohidrat' => '7.50',
                'protein' => '0.00',
                'idjenis_pangan' => 7,
            ),
            148 => 
            array (
                'idpangan' => 149,
                'nama_pangan' => 'Krupuk',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '5.83',
                'lemak' => '0.00',
                'karbohidrat' => '1.10',
                'protein' => '0.13',
                'idjenis_pangan' => 9,
            ),
            149 => 
            array (
                'idpangan' => 150,
                'nama_pangan' => 'Kopi',
                'takaran' => 'sdm',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '1.00',
                'lemak' => '0.00',
                'karbohidrat' => '1.00',
                'protein' => '0.13',
                'idjenis_pangan' => 9,
            ),
            150 => 
            array (
                'idpangan' => 151,
                'nama_pangan' => 'Bakwan',
                'takaran' => 'Potong',
                'urt' => 1,
                'gram' => '51.00',
                'kalori' => '274.50',
                'lemak' => '20.70',
                'karbohidrat' => '20.00',
                'protein' => '2.70',
                'idjenis_pangan' => 1,
            ),
            151 => 
            array (
                'idpangan' => 152,
                'nama_pangan' => 'Durian',
                'takaran' => 'Biji',
                'urt' => 1,
                'gram' => '16.70',
                'kalori' => '13.33',
                'lemak' => '0.00',
                'karbohidrat' => '3.33',
                'protein' => '0.00',
                'idjenis_pangan' => 8,
            ),
            152 => 
            array (
                'idpangan' => 153,
                'nama_pangan' => 'Manggis',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '40.00',
                'kalori' => '25.00',
                'lemak' => '1.00',
                'karbohidrat' => '6.00',
                'protein' => '1.00',
                'idjenis_pangan' => 8,
            ),
            153 => 
            array (
                'idpangan' => 154,
                'nama_pangan' => 'BLEWAH',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '70.00',
                'kalori' => '17.50',
                'lemak' => '1.00',
                'karbohidrat' => '5.00',
                'protein' => '1.00',
                'idjenis_pangan' => 8,
            ),
            154 => 
            array (
                'idpangan' => 155,
                'nama_pangan' => 'BUAH NAGA',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '51.00',
                'lemak' => '0.38',
                'karbohidrat' => '12.38',
                'protein' => '0.78',
                'idjenis_pangan' => 8,
            ),
            155 => 
            array (
                'idpangan' => 156,
                'nama_pangan' => 'Kelor',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '60.00',
                'lemak' => '0.93',
                'karbohidrat' => '11.15',
                'protein' => '5.27',
                'idjenis_pangan' => 8,
            ),
            156 => 
            array (
                'idpangan' => 157,
                'nama_pangan' => 'Kurma',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '12.20',
                'kalori' => '23.00',
                'lemak' => '0.03',
                'karbohidrat' => '6.23',
                'protein' => '0.20',
                'idjenis_pangan' => 8,
            ),
            157 => 
            array (
                'idpangan' => 158,
                'nama_pangan' => 'Duku',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '68.00',
                'lemak' => '0.43',
                'karbohidrat' => '17.06',
                'protein' => '0.85',
                'idjenis_pangan' => 8,
            ),
            158 => 
            array (
                'idpangan' => 159,
                'nama_pangan' => 'Perkedel',
                'takaran' => 'Potong',
                'urt' => 1,
                'gram' => '14.70',
                'kalori' => '21.00',
                'lemak' => '1.12',
                'karbohidrat' => '2.48',
                'protein' => '0.26',
                'idjenis_pangan' => 2,
            ),
            159 => 
            array (
                'idpangan' => 160,
                'nama_pangan' => 'Cendol',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '300.00',
                'kalori' => '465.00',
                'lemak' => '19.11',
                'karbohidrat' => '70.47',
                'protein' => '5.60',
                'idjenis_pangan' => 8,
            ),
            160 => 
            array (
                'idpangan' => 161,
                'nama_pangan' => 'Pindang',
                'takaran' => 'Potong',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '153.00',
                'lemak' => '2.80',
                'karbohidrat' => '0.00',
                'protein' => '30.00',
                'idjenis_pangan' => 3,
            ),
            161 => 
            array (
                'idpangan' => 162,
                'nama_pangan' => 'Mujair',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '169.00',
                'lemak' => '6.92',
                'karbohidrat' => '2.22',
                'protein' => '24.55',
                'idjenis_pangan' => 3,
            ),
            162 => 
            array (
                'idpangan' => 163,
                'nama_pangan' => 'Kecambah',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '29.00',
                'lemak' => '0.48',
                'karbohidrat' => '4.69',
                'protein' => '3.59',
                'idjenis_pangan' => 8,
            ),
            163 => 
            array (
                'idpangan' => 164,
                'nama_pangan' => 'Lele',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '85.00',
                'kalori' => '204.00',
                'lemak' => '12.35',
                'karbohidrat' => '7.26',
                'protein' => '14.39',
                'idjenis_pangan' => 3,
            ),
            164 => 
            array (
                'idpangan' => 165,
                'nama_pangan' => 'Kikil',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '240.00',
                'kalori' => '240.00',
                'lemak' => '10.86',
                'karbohidrat' => '9.97',
                'protein' => '26.12',
                'idjenis_pangan' => 3,
            ),
            165 => 
            array (
                'idpangan' => 166,
                'nama_pangan' => 'Belut',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '92.00',
                'lemak' => '1.42',
                'karbohidrat' => '0.00',
                'protein' => '18.51',
                'idjenis_pangan' => 3,
            ),
            166 => 
            array (
                'idpangan' => 167,
                'nama_pangan' => 'Telur Dadar',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '61.00',
                'kalori' => '93.00',
                'lemak' => '7.33',
                'karbohidrat' => '0.42',
                'protein' => '6.48',
                'idjenis_pangan' => 3,
            ),
            167 => 
            array (
                'idpangan' => 168,
                'nama_pangan' => 'Energen',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '30.00',
                'kalori' => '130.00',
                'lemak' => '3.50',
                'karbohidrat' => '24.00',
                'protein' => '1.00',
                'idjenis_pangan' => 1,
            ),
            168 => 
            array (
                'idpangan' => 169,
                'nama_pangan' => 'Soto Ayam',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '241.00',
                'kalori' => '312.00',
                'lemak' => '14.92',
                'karbohidrat' => '19.55',
                'protein' => '24.01',
                'idjenis_pangan' => 3,
            ),
            169 => 
            array (
                'idpangan' => 170,
                'nama_pangan' => 'Soto Daging',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '241.00',
                'kalori' => '219.00',
                'lemak' => '11.51',
                'karbohidrat' => '10.77',
                'protein' => '18.25',
                'idjenis_pangan' => 3,
            ),
            170 => 
            array (
                'idpangan' => 171,
                'nama_pangan' => 'Rempeyek',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '9.00',
                'kalori' => '44.00',
                'lemak' => '1.71',
                'karbohidrat' => '6.41',
                'protein' => '0.68',
                'idjenis_pangan' => 9,
            ),
            171 => 
            array (
                'idpangan' => 172,
                'nama_pangan' => 'Telur Ceplok',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '201.00',
                'lemak' => '15.31',
                'karbohidrat' => '0.88',
                'protein' => '13.63',
                'idjenis_pangan' => 3,
            ),
            172 => 
            array (
                'idpangan' => 173,
                'nama_pangan' => 'Spaghetti',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '450.00',
                'kalori' => '220.00',
                'lemak' => '1.00',
                'karbohidrat' => '45.00',
                'protein' => '7.00',
                'idjenis_pangan' => 1,
            ),
            173 => 
            array (
                'idpangan' => 174,
                'nama_pangan' => 'Mie goreng',
                'takaran' => 'Bungkus',
                'urt' => 1,
                'gram' => '85.00',
                'kalori' => '380.00',
                'lemak' => '14.00',
                'karbohidrat' => '54.00',
                'protein' => '8.00',
                'idjenis_pangan' => 1,
            ),
            174 => 
            array (
                'idpangan' => 175,
                'nama_pangan' => 'Nasi Goreng',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '198.00',
                'kalori' => '333.00',
                'lemak' => '12.34',
                'karbohidrat' => '41.70',
                'protein' => '12.47',
                'idjenis_pangan' => 9,
            ),
            175 => 
            array (
                'idpangan' => 176,
                'nama_pangan' => 'Madu',
                'takaran' => 'Sdm',
                'urt' => 1,
                'gram' => '14.44',
                'kalori' => '64.00',
                'lemak' => '0.00',
                'karbohidrat' => '17.30',
                'protein' => '0.06',
                'idjenis_pangan' => 9,
            ),
            176 => 
            array (
                'idpangan' => 177,
                'nama_pangan' => 'Pir',
                'takaran' => 'Buah sedang',
                'urt' => 1,
                'gram' => '450.00',
                'kalori' => '96.00',
                'lemak' => '0.20',
                'karbohidrat' => '25.66',
                'protein' => '0.63',
                'idjenis_pangan' => 8,
            ),
            177 => 
            array (
                'idpangan' => 178,
                'nama_pangan' => 'Nasi padang',
                'takaran' => 'Piring',
                'urt' => 1,
                'gram' => '250.00',
                'kalori' => '664.00',
                'lemak' => '15.00',
                'karbohidrat' => '70.00',
                'protein' => '70.00',
                'idjenis_pangan' => 9,
            ),
            178 => 
            array (
                'idpangan' => 179,
                'nama_pangan' => 'Biskuit',
                'takaran' => 'Biji',
                'urt' => 5,
                'gram' => '25.00',
                'kalori' => '110.00',
                'lemak' => '3.00',
                'karbohidrat' => '19.00',
                'protein' => '2.00',
                'idjenis_pangan' => 1,
            ),
            179 => 
            array (
                'idpangan' => 180,
                'nama_pangan' => 'Bawang Merah',
                'takaran' => 'Buah kecil',
                'urt' => 1,
                'gram' => '14.00',
                'kalori' => '6.00',
                'lemak' => '0.01',
                'karbohidrat' => '1.42',
                'protein' => '0.13',
                'idjenis_pangan' => 9,
            ),
            180 => 
            array (
                'idpangan' => 181,
                'nama_pangan' => 'Bawang Putih',
                'takaran' => 'Siung',
                'urt' => 1,
                'gram' => '5.96',
                'kalori' => '4.00',
                'lemak' => '0.02',
                'karbohidrat' => '0.99',
                'protein' => '0.19',
                'idjenis_pangan' => 9,
            ),
            181 => 
            array (
                'idpangan' => 182,
                'nama_pangan' => 'Daging Kambing',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '109.00',
                'lemak' => '2.31',
                'karbohidrat' => '0.00',
                'protein' => '20.60',
                'idjenis_pangan' => 3,
            ),
            182 => 
            array (
                'idpangan' => 183,
                'nama_pangan' => 'Krupuk Udang',
                'takaran' => 'Buah Sedang',
                'urt' => 1,
                'gram' => '6.50',
                'kalori' => '35.00',
                'lemak' => '2.29',
                'karbohidrat' => '3.26',
                'protein' => '0.43',
                'idjenis_pangan' => 9,
            ),
            183 => 
            array (
                'idpangan' => 184,
                'nama_pangan' => 'Hati Ayam',
                'takaran' => 'Potong Sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '116.00',
                'lemak' => '4.83',
                'karbohidrat' => '0.00',
                'protein' => '16.92',
                'idjenis_pangan' => 3,
            ),
            184 => 
            array (
                'idpangan' => 185,
                'nama_pangan' => 'Rujak Cingur',
                'takaran' => 'Piring',
                'urt' => 1,
                'gram' => '200.00',
                'kalori' => '249.00',
                'lemak' => '12.71',
                'karbohidrat' => '22.53',
                'protein' => '13.68',
                'idjenis_pangan' => 9,
            ),
            185 => 
            array (
                'idpangan' => 186,
                'nama_pangan' => 'Brokoli',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '87.00',
                'lemak' => '4.33',
                'karbohidrat' => '11.24',
                'protein' => '3.70',
                'idjenis_pangan' => 8,
            ),
            186 => 
            array (
                'idpangan' => 187,
                'nama_pangan' => 'Roti Tawar',
                'takaran' => 'Lembar',
                'urt' => 1,
                'gram' => '40.00',
                'kalori' => '106.00',
                'lemak' => '0.52',
                'karbohidrat' => '22.32',
                'protein' => '3.84',
                'idjenis_pangan' => 1,
            ),
            187 => 
            array (
                'idpangan' => 188,
                'nama_pangan' => 'Teh',
                'takaran' => 'Gelas',
                'urt' => 1,
                'gram' => '177.00',
                'kalori' => '55.00',
                'lemak' => '0.00',
                'karbohidrat' => '14.36',
                'protein' => '0.00',
                'idjenis_pangan' => 9,
            ),
            188 => 
            array (
                'idpangan' => 189,
                'nama_pangan' => 'Cabe Besar',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '31.00',
                'lemak' => '0.30',
                'karbohidrat' => '7.30',
                'protein' => '1.00',
                'idjenis_pangan' => 8,
            ),
            189 => 
            array (
                'idpangan' => 190,
                'nama_pangan' => 'Cabe Kecil',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '103.00',
                'lemak' => '2.40',
                'karbohidrat' => '19.90',
                'protein' => '4.70',
                'idjenis_pangan' => 8,
            ),
            190 => 
            array (
                'idpangan' => 191,
                'nama_pangan' => 'Tepung Beras',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '365.00',
                'lemak' => '1.40',
                'karbohidrat' => '80.00',
                'protein' => '6.00',
                'idjenis_pangan' => 1,
            ),
            191 => 
            array (
                'idpangan' => 192,
                'nama_pangan' => 'Tepung Terigu',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '350.00',
                'lemak' => '1.00',
                'karbohidrat' => '74.00',
                'protein' => '12.00',
                'idjenis_pangan' => 1,
            ),
            192 => 
            array (
                'idpangan' => 193,
                'nama_pangan' => 'Sereh',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '99.00',
                'lemak' => '0.49',
                'karbohidrat' => '25.31',
                'protein' => '1.82',
                'idjenis_pangan' => 9,
            ),
            193 => 
            array (
                'idpangan' => 194,
                'nama_pangan' => 'Kecap',
                'takaran' => 'Sdm',
                'urt' => 1,
                'gram' => '14.00',
                'kalori' => '60.00',
                'lemak' => '0.00',
                'karbohidrat' => '15.00',
                'protein' => '0.00',
                'idjenis_pangan' => 6,
            ),
            194 => 
            array (
                'idpangan' => 195,
                'nama_pangan' => 'Daun Kenikir',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '40.00',
                'lemak' => '0.45',
                'karbohidrat' => '6.93',
                'protein' => '3.81',
                'idjenis_pangan' => 8,
            ),
            195 => 
            array (
                'idpangan' => 196,
                'nama_pangan' => 'Kacang Koro',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '25.00',
                'kalori' => '110.00',
                'lemak' => '4.00',
                'karbohidrat' => '14.00',
                'protein' => '5.00',
                'idjenis_pangan' => 6,
            ),
            196 => 
            array (
                'idpangan' => 197,
                'nama_pangan' => 'Jahe',
                'takaran' => 'Sdt',
                'urt' => 1,
                'gram' => '1.00',
                'kalori' => '2.00',
                'lemak' => '0.02',
                'karbohidrat' => '0.36',
                'protein' => '0.04',
                'idjenis_pangan' => 9,
            ),
            197 => 
            array (
                'idpangan' => 198,
                'nama_pangan' => 'Daun Kenikir',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '40.00',
                'lemak' => '0.45',
                'karbohidrat' => '6.93',
                'protein' => '3.81',
                'idjenis_pangan' => 8,
            ),
            198 => 
            array (
                'idpangan' => 199,
                'nama_pangan' => 'Bihun',
                'takaran' => 'Mangkok',
                'urt' => 1,
                'gram' => '176.00',
                'kalori' => '192.00',
                'lemak' => '0.35',
                'karbohidrat' => '43.82',
                'protein' => '1.60',
                'idjenis_pangan' => 1,
            ),
            199 => 
            array (
                'idpangan' => 200,
                'nama_pangan' => 'Ikan Bandeng',
                'takaran' => 'Ekor sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '148.00',
                'lemak' => '6.73',
                'karbohidrat' => '0.00',
                'protein' => '20.53',
                'idjenis_pangan' => 3,
            ),
            200 => 
            array (
                'idpangan' => 201,
                'nama_pangan' => 'Ikan Tuna',
                'takaran' => 'Ekor sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '108.00',
                'lemak' => '0.95',
                'karbohidrat' => '0.00',
                'protein' => '23.38',
                'idjenis_pangan' => 3,
            ),
            201 => 
            array (
                'idpangan' => 202,
                'nama_pangan' => 'Bengkoang',
                'takaran' => 'Buah sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '38.00',
                'lemak' => '0.09',
                'karbohidrat' => '8.82',
                'protein' => '0.72',
                'idjenis_pangan' => 8,
            ),
            202 => 
            array (
                'idpangan' => 203,
                'nama_pangan' => 'Tempe Benguk',
                'takaran' => 'Potong sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '141.00',
                'lemak' => '1.30',
                'karbohidrat' => '23.30',
                'protein' => '10.20',
                'idjenis_pangan' => 6,
            ),
            203 => 
            array (
                'idpangan' => 204,
                'nama_pangan' => 'Sawi Putih',
                'takaran' => 'Ikat',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '12.00',
                'lemak' => '0.17',
                'karbohidrat' => '2.23',
                'protein' => '1.10',
                'idjenis_pangan' => 8,
            ),
            204 => 
            array (
                'idpangan' => 205,
                'nama_pangan' => 'Ampela',
                'takaran' => 'Porsi',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '145.00',
                'lemak' => '2.66',
                'karbohidrat' => '0.00',
                'protein' => '30.14',
                'idjenis_pangan' => 3,
            ),
            205 => 
            array (
                'idpangan' => 206,
                'nama_pangan' => 'Pisang Ambon',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '99.00',
                'lemak' => '0.20',
                'karbohidrat' => '25.80',
                'protein' => '1.20',
                'idjenis_pangan' => 8,
            ),
            206 => 
            array (
                'idpangan' => 207,
                'nama_pangan' => 'Pisang Mas',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '127.00',
                'lemak' => '0.20',
                'karbohidrat' => '33.60',
                'protein' => '1.40',
                'idjenis_pangan' => 8,
            ),
            207 => 
            array (
                'idpangan' => 208,
                'nama_pangan' => 'Pisang Raja Uli',
                'takaran' => 'Buah',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '146.00',
                'lemak' => '0.20',
                'karbohidrat' => '38.20',
                'protein' => '2.00',
                'idjenis_pangan' => 8,
            ),
            208 => 
            array (
                'idpangan' => 209,
                'nama_pangan' => 'Nila',
                'takaran' => 'Ekor sedang',
                'urt' => 1,
                'gram' => '100.00',
                'kalori' => '96.00',
                'lemak' => '1.70',
                'karbohidrat' => '0.00',
                'protein' => '20.08',
                'idjenis_pangan' => 3,
            ),
            209 => 
            array (
                'idpangan' => 210,
                'nama_pangan' => 'Susu kental manis',
                'takaran' => 'Sachet',
                'urt' => 1,
                'gram' => '40.00',
                'kalori' => '180.00',
                'lemak' => '30.00',
                'karbohidrat' => '67.00',
                'protein' => '3.00',
                'idjenis_pangan' => 9,
            ),
            210 => 
            array (
                'idpangan' => 211,
                'nama_pangan' => 'Garam',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '0.00',
                'lemak' => '0.00',
                'karbohidrat' => '0.00',
                'protein' => '0.00',
                'idjenis_pangan' => 9,
            ),
            211 => 
            array (
                'idpangan' => 212,
                'nama_pangan' => 'terasi',
                'takaran' => 'sdm',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '15.50',
                'lemak' => '0.29',
                'karbohidrat' => '0.99',
                'protein' => '2.23',
                'idjenis_pangan' => 9,
            ),
            212 => 
            array (
                'idpangan' => 213,
                'nama_pangan' => 'Lengkuas',
                'takaran' => 'sdm',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '1.20',
                'lemak' => '0.27',
                'karbohidrat' => '2.19',
                'protein' => '0.72',
                'idjenis_pangan' => 9,
            ),
            213 => 
            array (
                'idpangan' => 214,
                'nama_pangan' => 'Ketumbar',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '2.00',
                'kalori' => '0.46',
                'lemak' => '0.01',
                'karbohidrat' => '0.07',
                'protein' => '0.40',
                'idjenis_pangan' => 9,
            ),
            214 => 
            array (
                'idpangan' => 215,
                'nama_pangan' => 'Merica',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '3.00',
                'kalori' => '10.00',
                'lemak' => '0.00',
                'karbohidrat' => '2.00',
                'protein' => '0.00',
                'idjenis_pangan' => 9,
            ),
            215 => 
            array (
                'idpangan' => 216,
                'nama_pangan' => 'Gula Jawa',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '4.00',
                'kalori' => '11.00',
                'lemak' => '0.00',
                'karbohidrat' => '2.92',
                'protein' => '0.00',
                'idjenis_pangan' => 7,
            ),
            216 => 
            array (
                'idpangan' => 217,
                'nama_pangan' => 'kluwek',
                'takaran' => 'sdm',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '31.00',
                'lemak' => '2.40',
                'karbohidrat' => '1.35',
                'protein' => '1.00',
                'idjenis_pangan' => 9,
            ),
            217 => 
            array (
                'idpangan' => 218,
                'nama_pangan' => 'Temu Kunci',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '10.00',
                'kalori' => '2.00',
                'lemak' => '0.20',
                'karbohidrat' => '0.36',
                'protein' => '0.20',
                'idjenis_pangan' => 9,
            ),
            218 => 
            array (
                'idpangan' => 219,
                'nama_pangan' => 'Kencur',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '10.25',
                'lemak' => '0.00',
                'karbohidrat' => '2.25',
                'protein' => '0.21',
                'idjenis_pangan' => 9,
            ),
            219 => 
            array (
                'idpangan' => 220,
                'nama_pangan' => 'Kunyit',
                'takaran' => 'sdt',
                'urt' => 1,
                'gram' => '5.00',
                'kalori' => '17.70',
                'lemak' => '0.49',
                'karbohidrat' => '3.25',
                'protein' => '0.39',
                'idjenis_pangan' => 9,
            ),
            220 => 
            array (
                'idpangan' => 221,
                'nama_pangan' => 'Bumbu Pecel',
                'takaran' => 'sdm',
                'urt' => 1,
                'gram' => '12.00',
                'kalori' => '79.00',
                'lemak' => '5.16',
                'karbohidrat' => '6.81',
                'protein' => '2.66',
                'idjenis_pangan' => 9,
            ),
            221 => 
            array (
                'idpangan' => 222,
                'nama_pangan' => 'Daun Jeruk Purut',
                'takaran' => 'helai daun',
                'urt' => 1,
                'gram' => '2.00',
                'kalori' => '2.40',
                'lemak' => '0.01',
                'karbohidrat' => '0.29',
                'protein' => '0.06',
                'idjenis_pangan' => 9,
            ),
        ));
        
        
    }
}